In [1]:
# Genre classification using RF

In [2]:
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from sklearn.inspection import permutation_importance
from sklearn.model_selection import RepeatedStratifiedKFold

In [3]:
# load genre labels 

df_verse_labels = pd.read_csv('TAPA Paper_ Genre Labels - Verse.csv')
df_prose_labels = pd.read_csv('TAPA Paper_ Genre Labels - Prose.csv')
df_verse_labels.head()

    Author       Work  Genre              File Name
0  Plautus  Amphitruo  drama  plautus.amphitruo.txt
1  Plautus   Asinaria  drama   plautus.asinaria.txt
2  Plautus  Aulularia  drama  plautus.aulularia.txt
3  Plautus  Bacchides  drama  plautus.bacchides.txt
4  Plautus    Captivi  drama    plautus.captivi.txt

In [4]:
df_prose_labels.head()

,Author,Work,Genre,File Name
0,Augustine,Epistulae (1-10),epistolography,augustine.epistulae_1_10.part.1.txt
1,Augustine,Epistulae (11-20),epistolography,augustine.epistulae_11_20.part.2.txt
2,Augustine,Epistulae (21-30),epistolography,augustine.epistulae_21_30.part.3.txt
3,Augustine,Epistulae (31-40),epistolography,augustine.epistulae_31_40.part.4.txt
4,Augustine,Epistulae (41-50),epistolography,augustine.epistulae_41_50.part.5.txt

In [5]:
# load stylometric data 

df_verse_data = pd.read_csv('20250922_172341-raw-verse.csv')
df_verse_data = df_verse_data.rename(columns={'Unnamed: 0': 'File Name'}) 
df_prose_data = pd.read_csv('20250922_174146-raw-prose.csv')
df_prose_data = df_prose_data.rename(columns={'Unnamed: 0': 'File Name'}) 

df_verse_data.head()

,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,antequam,atque_consonant,conjunction,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,anonymous.laudes_domini.txt,913,42,21.738095,0.357143,8.772727,0,0,1,86,...,29,19,0,0,0,0,4,3,0,7
1,catullus.carmina.64.txt,2445,109,22.431193,0.357798,8.140351,3,0,0,130,...,58,78,0,0,0,0,12,2,1,16
2,catullus.carmina.65_116.txt,4132,202,20.455446,0.465347,6.924812,3,0,5,318,...,210,143,0,2,3,0,22,48,1,27
3,catullus.carmina1_63.txt,6361,395,15.959494,0.283544,5.720000,10,0,8,567,...,285,195,1,3,2,0,24,61,10,59
4,claudian.carmina_minora.txt,10828,642,16.852025,0.218069,6.248677,13,0,6,933,...,212,341,0,0,5,0,39,46,9,26

In [6]:
df_prose_data.head()

,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,antequam,atque_consonant,conjunction,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,ammianus.rerum_gestarum.part.14.txt,8221,269,30.505576,0.605948,5.661017,27,1,11,719,...,60,527,0,47,1,0,38,31,19,108
1,ammianus.rerum_gestarum.part.15.txt,6872,247,27.740891,0.481781,5.647399,25,3,2,576,...,58,434,0,22,0,0,37,19,21,105
2,ammianus.rerum_gestarum.part.16.txt,7676,243,31.448560,0.547325,5.472222,25,2,2,673,...,79,470,0,40,1,0,54,27,24,95
3,ammianus.rerum_gestarum.part.17.txt,7396,266,27.755639,0.503759,5.323077,20,2,4,641,...,65,400,0,18,0,0,39,27,21,93
4,ammianus.rerum_gestarum.part.18.txt,5042,152,33.131579,0.578947,5.231343,11,0,2,423,...,50,318,0,16,2,0,16,17,33,55

In [7]:
# merge verse genre labels

df_verse = pd.merge(df_verse_labels, df_verse_data, on='File Name')
df_verse.to_csv('verse_labeled.csv')
df_verse.head()

,Author,Work,Genre,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,Plautus,Amphitruo,drama,plautus.amphitruo.txt,9340,987,9.460993,0.198582,4.879668,17,...,738,326,3,2,21,0,44,123,3,139
1,Plautus,Asinaria,drama,plautus.asinaria.txt,7632,901,8.467259,0.178690,4.354167,19,...,622,244,4,0,23,0,37,130,5,105
2,Plautus,Aulularia,drama,plautus.aulularia.txt,6561,744,8.813172,0.186828,4.760479,9,...,582,210,4,0,18,0,24,89,5,89
3,Plautus,Bacchides,drama,plautus.bacchides.txt,9458,1182,7.996616,0.170051,4.745690,13,...,728,316,5,1,15,0,39,110,6,152
4,Plautus,Captivi,drama,plautus.captivi.txt,8288,819,10.117216,0.230769,4.714894,20,...,691,335,2,0,15,1,37,113,7,112

In [8]:
# merge prose genre labels

df_prose = pd.merge(df_prose_labels, df_prose_data, on='File Name')
df_prose.to_csv('prose_labeled.csv')
df_prose.head()

,Author,Work,Genre,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,Augustine,Epistulae (1-10),epistolography,augustine.epistulae_1_10.part.1.txt,4791,270,17.722222,0.474074,5.107477,22,...,207,249,3,17,0,0,26,58,37,68
1,Augustine,Epistulae (11-20),epistolography,augustine.epistulae_11_20.part.2.txt,4815,195,24.682051,0.625641,5.363636,10,...,212,278,0,21,0,0,13,84,29,66
2,Augustine,Epistulae (21-30),epistolography,augustine.epistulae_21_30.part.3.txt,13013,476,27.342437,0.581933,6.191489,27,...,616,767,1,10,2,0,39,173,66,165
3,Augustine,Epistulae (31-40),epistolography,augustine.epistulae_31_40.part.4.txt,14078,615,22.868293,0.557724,5.590510,46,...,435,829,0,15,0,1,56,185,65,190
4,Augustine,Epistulae (41-50),epistolography,augustine.epistulae_41_50.part.5.txt,12367,456,27.114035,0.629386,5.595978,46,...,326,874,1,16,0,0,60,190,49,134

In [9]:
import pandas as pd
import numpy as np
from collections import Counter

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from sklearn.inspection import permutation_importance

def train_evaluate_genre_100times_with_misclassified(df: pd.DataFrame, 
                                                     target_genre: str,
                                                     base_random_state: int = 42,
                                                     n_estimators: int = 100):
    """
    Runs a one-vs-rest random forest classification 100 times, each time with 
    a different random seed for the 5-fold stratified cross-validation. 
    Reports mean/std for accuracy and F1 across all trials, and mean/std for 
    Gini and permutation importances across all trials.
    
    Also tracks how many times each text is misclassified across all 100 trials
    (500 folds total) and reports any text that is misclassified at least once.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing columns:
            - "Genre" (the class label)
            - "File Name" (document identity)
            - 26 numerical features in columns "sentence_length" to "ut".
    target_genre : str
        The genre to treat as the positive class in the one-vs-rest setting.
    base_random_state : int, optional
        Starting random state for reproducibility, by default 42.
        Trial i will use random_state = base_random_state + i
    n_estimators : int, optional
        Number of trees in the random forest, by default 100.

    Returns
    -------
    None
        Prints out:
            (1) Mean/stdev of accuracy and macro-F1 (across 100 trials,
                each trial does 5-fold CV internally)
            (2) Mean/stdev of Gini importance across 100 final models
            (3) Mean/stdev of permutation importance across 100 final models
            (4) A report of which texts (File Name) were misclassified at 
                least once and how many times total.
    """

    # Identify the feature columns
    feature_cols = df.loc[:, "sentence_length":"ut"].columns
    X = df[feature_cols].values
    
    # Convert Genre to binary label (one-vs-rest)
    y = (df["Genre"] == target_genre).astype(int).values
    
    # Also store file names for tracking misclassifications
    file_names = df["File Name"].values

    # For reproducibility, define 100 different seeds
    random_seeds = [base_random_state + i for i in range(100)]
    
    # Collect metrics and importances across the 100 trials
    trial_accuracies = []
    trial_f1s = []
    # Gini importances and Permutation importances are shape (100, n_features)
    gini_all = []
    perm_all = []
    
    # Counter to track total misclassifications across all folds and trials
    misclassified_counter = Counter()

    for seed in random_seeds:
        # =========================================================
        # 1) 5-fold Stratified CV with this random seed
        # =========================================================
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)

        fold_accuracies = []
        fold_f1s = []

        for train_idx, test_idx in skf.split(X, y):
            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]
            file_test = file_names[test_idx]

            # Train the random forest
            rf = RandomForestClassifier(n_estimators=n_estimators, 
                                        random_state=seed)
            rf.fit(X_train, y_train)

            # Predictions
            y_pred = rf.predict(X_test)
            fold_accuracies.append(accuracy_score(y_test, y_pred))
            fold_f1s.append(f1_score(y_test, y_pred, average="macro"))

            # ----------------------------------------------------
            # Track which texts are misclassified in this fold
            # ----------------------------------------------------
            mis_mask = (y_pred != y_test)
            mis_file_names = file_test[mis_mask]
            for f_name in mis_file_names:
                misclassified_counter[f_name] += 1
        
        # Mean metrics across the 5 folds for this trial
        trial_accuracies.append(np.mean(fold_accuracies))
        trial_f1s.append(np.mean(fold_f1s))

        # =========================================================
        # 2) Retrain on entire dataset for final feature importance
        #    (this is still the same "trial" seed)
        # =========================================================
        final_rf = RandomForestClassifier(n_estimators=n_estimators,
                                          random_state=seed)
        final_rf.fit(X, y)

        # Gini importances
        gini_importances = final_rf.feature_importances_

        # Permutation importances
        perm_result = permutation_importance(
            estimator=final_rf,
            X=X,
            y=y,
            n_repeats=20,
            random_state=seed
        )
        perm_importances = perm_result.importances_mean  # average over repeats

        gini_all.append(gini_importances)
        perm_all.append(perm_importances)
    
    # ----------------------------------------------------
    # Compute overall mean/std of accuracy & F1 across 100 trials
    # ----------------------------------------------------
    mean_acc_100 = np.mean(trial_accuracies)
    std_acc_100  = np.std(trial_accuracies)
    mean_f1_100  = np.mean(trial_f1s)
    std_f1_100   = np.std(trial_f1s)

    print("=== Results Over 100 Trials (Each w/ 5-fold CV) ===")
    print(f"Accuracy: {mean_acc_100:.3f} ± {std_acc_100:.3f}")
    print(f"Macro F1: {mean_f1_100:.3f} ± {std_f1_100:.3f}\n")
    
    # ----------------------------------------------------
    # Compute overall mean/std of Gini and Permutation importances
    # ----------------------------------------------------
    gini_all = np.array(gini_all)  # shape = (100, n_features)
    perm_all = np.array(perm_all)  # shape = (100, n_features)

    gini_mean = gini_all.mean(axis=0)
    gini_std  = gini_all.std(axis=0)

    perm_mean = perm_all.mean(axis=0)
    perm_std  = perm_all.std(axis=0)

    # Make a dataframe for Gini importances
    gini_df = pd.DataFrame({
        "Feature Name": feature_cols,
        "Mean Gini": gini_mean,
        "Std Gini": gini_std
    }).sort_values("Mean Gini", ascending=False)

    # Make a dataframe for Permutation importances
    perm_df = pd.DataFrame({
        "Feature Name": feature_cols,
        "Mean Permutation Importance": perm_mean,
        "Std Permutation Importance": perm_std
    }).sort_values("Mean Permutation Importance", ascending=False)

    print("=== Gini Importances (Mean ± Std over 100 Trials) ===")
    print(gini_df.to_string(index=False))
    print()

    print("=== Permutation Importances (Mean ± Std over 100 Trials) ===")
    print(perm_df.to_string(index=False))
    print()

    # ----------------------------------------------------
    # 3) Report misclassified texts (across all 100 trials)
    # ----------------------------------------------------
    misclass_list = [
        (fname, count) 
        for fname, count in misclassified_counter.items() 
        if count > 0
    ]

    # Sort by descending times misclassified
    misclass_list.sort(key=lambda x: x[1], reverse=True)

    if len(misclass_list) > 0:
        misclass_df = pd.DataFrame(misclass_list, 
                                   columns=["File Name", "Times Misclassified"])
        print("=== Misclassified Texts Over 100 Trials ===")
        print(misclass_df.to_string(index=False))
    else:
        print("No texts were misclassified in any fold of any trial!")

In [10]:
train_evaluate_genre_100times_with_misclassified(df_verse, 'drama', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.965 ± 0.006
Macro F1: 0.927 ± 0.013

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
             interrogative   0.209114  0.021365
           sentence_length   0.131830  0.016193
                      iste   0.129951  0.015328
                  personal   0.071309  0.012415
             demonstrative   0.068226  0.013507
                      quin   0.045898  0.009562
fraction_sentence_relative   0.043623  0.006589
                        si   0.040844  0.009010
                 priusquam   0.035357  0.009188
                        ut   0.025687  0.006133
                      idem   0.021337  0.005127
                 gerundive   0.021236  0.002772
               conjunction   0.018539  0.002853
               superlative   0.018443  0.002451
                cum_clause   0.017069  0.003022
                  antequam   0.014629  0.002260
                      ipse   0.013324  0.001955
               preposition   0.012665  0.002272
    relative_clause_length   0.012661  0.002438
            o_interjection   0.012424  0.002178
                 reflexive   0.010255  0.002567
                     alius   0.008655  0.002619
                       dum   0.007630  0.001667
           atque_consonant   0.005597  0.001352
                    quidam   0.003549  0.001044
                  quominus   0.000148  0.000138

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
             interrogative                     0.026583                    0.004225
                      iste                     0.003079                    0.001456
                  antequam                     0.002835                    0.001864
               superlative                     0.002342                    0.002025
                 gerundive                     0.001799                    0.001554
                  personal                     0.000011                    0.000106
           sentence_length                     0.000009                    0.000060
            o_interjection                     0.000000                    0.000000
                        si                     0.000000                    0.000000
                 reflexive                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                    quidam                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
               preposition                     0.000000                    0.000000
                      ipse                     0.000000                    0.000000
fraction_sentence_relative                     0.000000                    0.000000
                      idem                     0.000000                    0.000000
                       dum                     0.000000                    0.000000
             demonstrative                     0.000000                    0.000000
                cum_clause                     0.000000                    0.000000
               conjunction                     0.000000                    0.000000
           atque_consonant                     0.000000                    0.000000
                     alius                     0.000000                    0.000000
    relative_clause_length                     0.000000                    0.000000
                        ut                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                     File Name  Times Misclassified
              seneca.medea.txt                  100
            seneca.octavia.txt                  100
            seneca.oedipus.txt                   99
         seneca.phoenissae.txt                   98
           persius.satires.txt                   98
           seneca.thyestes.txt                   90
ovid.heroides.part.2.16-21.txt                   74
            seneca.troades.txt                   70
        propertius.elegies.txt                   30
 ovid.heroides.part.1.1-15.txt                   30
          seneca.agamemnon.txt                   15
            seneca.phaedra.txt                    8
            horace.satires.txt                    8
   seneca.hercules_oetaeus.txt                    3
    seneca.hercules_furens.txt                    2
           juvenal.satires.txt                    1

In [11]:
train_evaluate_genre_100times_with_misclassified(df_verse, 'epic', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.864 ± 0.012
Macro F1: 0.862 ± 0.012

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
                  personal   0.152267  0.009387
           sentence_length   0.092796  0.006739
    relative_clause_length   0.080509  0.006903
                      iste   0.076259  0.007751
             interrogative   0.068481  0.006118
               conjunction   0.061965  0.004656
                        si   0.061747  0.006501
               preposition   0.060961  0.003765
             demonstrative   0.050171  0.004914
                 reflexive   0.041791  0.002946
                        ut   0.038195  0.004026
                cum_clause   0.026558  0.002900
fraction_sentence_relative   0.021470  0.002333
            o_interjection   0.020542  0.001941
                 gerundive   0.020380  0.002030
                      idem   0.019844  0.002538
                      ipse   0.019744  0.001700
                       dum   0.017064  0.001746
                     alius   0.015672  0.001616
           atque_consonant   0.013052  0.001344
               superlative   0.012667  0.001327
                    quidam   0.011894  0.002132
                      quin   0.009099  0.001744
                  antequam   0.003068  0.000827
                 priusquam   0.002660  0.000877
                  quominus   0.001144  0.000409

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
                  personal                     0.045857                    0.009168
               preposition                     0.018709                    0.004243
           sentence_length                     0.004417                    0.002181
    relative_clause_length                     0.002857                    0.002773
               conjunction                     0.002504                    0.002258
             interrogative                     0.002239                    0.001288
                 reflexive                     0.000130                    0.000440
             demonstrative                     0.000107                    0.000413
                      iste                     0.000062                    0.000237
                        si                     0.000006                    0.000064
               superlative                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                    quidam                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
                      ipse                     0.000000                    0.000000
            o_interjection                     0.000000                    0.000000
fraction_sentence_relative                     0.000000                    0.000000
                      idem                     0.000000                    0.000000
                 gerundive                     0.000000                    0.000000
                       dum                     0.000000                    0.000000
                cum_clause                     0.000000                    0.000000
           atque_consonant                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                     alius                     0.000000                    0.000000
                        ut                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                   File Name  Times Misclassified
                                      rutilius.de_reditu.txt                  100
                     juvencus.historia_evangelica.part.2.txt                  100
                                   statius.silvae.part.1.txt                  100
     claudian.panegyricus_dictus_manlio_theodoro_consuli.txt                  100
                                      horace.odes.part.4.txt                  100
                                   statius.silvae.part.2.txt                  100
                              ovid.metamorphoses.part.13.txt                  100
 claudian.panegyricus_de_sexto_consulatu_honorii_augusti.txt                  100
                                      horace.ars_poetica.txt                  100
                                       ovid.fasti.part.2.txt                   98
                             claudian.de_bello_gildonico.txt                   98
                                 horace.carmen_saeculare.txt                   90
                                         seneca.thyestes.txt                   90
                                               ovid.ibis.txt                   89
        claudian.epithalamium_de_nuptiis_honorii_augusti.txt                   88
                    claudian.de_raptu_proserpinae.part.1.txt                   87
                                 anonymous.laudes_domini.txt                   83
claudian.panegyricus_de_tertio_consulatu_honorii_augusti.txt                   82
                                      horace.odes.part.2.txt                   82
               claudian.in_consulatum_olybrii_et_probini.txt                   81
                               ovid.metamorphoses.part.9.txt                   80
                               dracontius.romulea.part.5.txt                   76
                              claudian.in_rufinum.part.1.txt                   72
                                     prudentius.epilogus.txt                   69
claudian.panegyricus_de_quarto_consulatu_honorii_augusti.txt                   69
                                  prudentius.dittochaeon.txt                   68
                                           horace.epodes.txt                   63
                               dracontius.romulea.part.4.txt                   62
                         ovid.medicamina_faciei_femineae.txt                   55
                                       ovid.fasti.part.4.txt                   53
                                      horace.odes.part.3.txt                   50
                               dracontius.romulea.part.1.txt                   48
                    claudian.de_raptu_proserpinae.part.3.txt                   46
                              lucan.bellum_civile.part.7.txt                   45
                                   statius.silvae.part.5.txt                   45
                                   statius.silvae.part.4.txt                   42
                               dracontius.romulea.part.3.txt                   42
                                       ovid.fasti.part.5.txt                   41
                                          ennius.annales.txt                   33
                                   statius.silvae.part.3.txt                   30
                              lucan.bellum_civile.part.8.txt                   28
                               dracontius.romulea.part.6.txt                   27
                                 claudian.carmina_minora.txt                   27
                              lucan.bellum_civile.part.5.txt                   21
                                       ovid.fasti.part.1.txt                   15
                               dracontius.romulea.part.2.txt                   12
                     juvencus.historia_evangelica.part.4.txt                   11
                                       ovid.fasti.part.3.txt                   10
                                     catullus.carmina.64.txt                    9
                    claudian.de_raptu_proserpinae.part.2.txt                    9
                     valerius_flaccus.argonautica.part.7.txt                    8
                               dracontius.romulea.part.7.txt                    8
                     valerius_flaccus.argonautica.part.8.txt                    7
                claudian.de_consulatu_stilichonis.part.1.txt                    7
                                       ovid.fasti.part.6.txt                    6
                        lucretius.de_rerum_natura.part.3.txt                    3
                               dracontius.romulea.part.9.txt                    3
                                          seneca.oedipus.txt                    2
                     juvencus.historia_evangelica.part.1.txt                    2
                            claudian.in_eutropium.part.1.txt                    1
                                        ennodius.carmina.txt                    1
                claudian.de_consulatu_stilichonis.part.3.txt                    1
                              lucan.bellum_civile.part.9.txt                    1
                                   prudentius.apotheosis.txt                    1
                                          seneca.octavia.txt                    1
                                  statius.thebaid.part.3.txt                    1
                                 martial.epigrams.part.4.txt                    1

In [12]:
train_evaluate_genre_100times_with_misclassified(df_verse, 'elegy', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.927 ± 0.006
Macro F1: 0.782 ± 0.025

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
    relative_clause_length   0.111411  0.007020
               conjunction   0.077678  0.007173
                        ut   0.067875  0.005928
                 gerundive   0.067790  0.005575
             demonstrative   0.062519  0.005720
                 reflexive   0.057226  0.005946
                      ipse   0.050069  0.004943
                  personal   0.049052  0.004364
           sentence_length   0.043343  0.005002
fraction_sentence_relative   0.043325  0.004867
           atque_consonant   0.043320  0.004709
               preposition   0.038152  0.004721
                    quidam   0.034516  0.003667
             interrogative   0.034419  0.004346
                     alius   0.033852  0.004415
                        si   0.028320  0.003605
                      idem   0.025054  0.003570
                       dum   0.023314  0.002771
               superlative   0.023307  0.003413
                      iste   0.021742  0.003152
                cum_clause   0.017721  0.002338
                      quin   0.015957  0.002934
            o_interjection   0.015355  0.002232
                 priusquam   0.010213  0.002192
                  quominus   0.003165  0.000906
                  antequam   0.001306  0.000568

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
    relative_clause_length                     0.028818                    0.007088
                        ut                     0.004267                    0.001875
               conjunction                     0.002692                    0.002114
             demonstrative                     0.002235                    0.001899
                    quidam                     0.002216                    0.001115
fraction_sentence_relative                     0.002081                    0.001979
                      ipse                     0.002019                    0.001963
                 gerundive                     0.001955                    0.002165
                       dum                     0.001786                    0.001636
             interrogative                     0.000671                    0.001353
                        si                     0.000397                    0.001018
           sentence_length                     0.000314                    0.000633
               superlative                     0.000261                    0.000734
                  personal                     0.000226                    0.000661
                 priusquam                     0.000173                    0.000756
                 reflexive                     0.000071                    0.000345
           atque_consonant                     0.000021                    0.000137
            o_interjection                     0.000015                    0.000149
               preposition                     0.000013                    0.000128
                      iste                     0.000000                    0.000000
                     alius                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                      idem                     0.000000                    0.000000
                cum_clause                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                          File Name  Times Misclassified
              ovid.fasti.part.4.txt                  100
ovid.medicamina_faciei_femineae.txt                  100
            ovid.tristia.part.2.txt                  100
               tibullus.elegies.txt                  100
        catullus.carmina.65_116.txt                  100
             ovid.amores.part.1.txt                  100
                      ovid.ibis.txt                  100
              ovid.fasti.part.2.txt                  100
             rutilius.de_reditu.txt                  100
     ovid.heroides.part.2.16-21.txt                   98
             propertius.elegies.txt                   95
              ovid.fasti.part.5.txt                   84
      ovid.heroides.part.1.1-15.txt                   82
            ovid.tristia.part.4.txt                   80
             ovid.amores.part.3.txt                   77
                juvenal.satires.txt                   74
              ovid.fasti.part.6.txt                   65
              ovid.fasti.part.1.txt                   35
        martial.epigrams.part.9.txt                   33
           ovid.ex_ponto.part.4.txt                   27
             ovid.amores.part.2.txt                   23
              ovid.fasti.part.3.txt                   13
            ovid.tristia.part.5.txt                    5
      phaedrus.fabulae_aesopiae.txt                    4
            ovid.tristia.part.3.txt                    2
                 horace.satires.txt                    1

In [13]:
train_evaluate_genre_100times_with_misclassified(df_verse, 'miscellaneous', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.861 ± 0.010
Macro F1: 0.713 ± 0.018

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
               preposition   0.138867  0.009573
               conjunction   0.084313  0.006914
                 reflexive   0.072935  0.005595
                  personal   0.063854  0.005177
                 gerundive   0.058699  0.005466
                      ipse   0.045115  0.003870
             demonstrative   0.044264  0.004481
           sentence_length   0.044095  0.003574
                        ut   0.043936  0.003843
            o_interjection   0.042450  0.003017
                        si   0.040374  0.003516
    relative_clause_length   0.037758  0.003085
             interrogative   0.035948  0.002979
           atque_consonant   0.035945  0.002984
                cum_clause   0.033714  0.002861
fraction_sentence_relative   0.032323  0.003391
                     alius   0.028237  0.002746
                      idem   0.024246  0.002552
                       dum   0.023042  0.002081
                      iste   0.020446  0.002500
                      quin   0.016932  0.002233
               superlative   0.016762  0.001783
                    quidam   0.012820  0.001647
                 priusquam   0.001867  0.000552
                  antequam   0.000893  0.000398
                  quominus   0.000164  0.000153

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
               preposition                     0.044583                    0.007484
            o_interjection                     0.011893                    0.001037
                        ut                     0.004774                    0.002407
           atque_consonant                     0.004096                    0.002871
               conjunction                     0.003494                    0.000399
                  personal                     0.002876                    0.002048
                 gerundive                     0.002808                    0.001888
                      ipse                     0.002750                    0.001077
                 reflexive                     0.001173                    0.001270
    relative_clause_length                     0.001002                    0.001316
             interrogative                     0.000239                    0.000601
           sentence_length                     0.000197                    0.000390
                        si                     0.000053                    0.000389
                cum_clause                     0.000034                    0.000300
                     alius                     0.000030                    0.000298
                      iste                     0.000004                    0.000043
                      idem                     0.000000                    0.000000
fraction_sentence_relative                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                       dum                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
                    quidam                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
               superlative                     0.000000                    0.000000
             demonstrative                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                   File Name  Times Misclassified
 claudian.panegyricus_de_sexto_consulatu_honorii_augusti.txt                  100
                                         horace.epistles.txt                  100
                                    catullus.carmina1_63.txt                  100
                                 claudian.carmina_minora.txt                  100
claudian.panegyricus_de_quarto_consulatu_honorii_augusti.txt                  100
                                        ennodius.carmina.txt                  100
                                      horace.ars_poetica.txt                  100
                                   statius.silvae.part.1.txt                  100
                                         vergil.eclogues.txt                  100
                                         persius.satires.txt                  100
                                 anonymous.laudes_domini.txt                  100
                               phaedrus.fabulae_aesopiae.txt                  100
     claudian.panegyricus_dictus_manlio_theodoro_consuli.txt                  100
                                 martial.epigrams.part.9.txt                  100
                                   statius.silvae.part.2.txt                  100
                                     prudentius.epilogus.txt                   99
        claudian.epithalamium_de_nuptiis_honorii_augusti.txt                   98
                               dracontius.romulea.part.5.txt                   98
                                 horace.carmen_saeculare.txt                   97
                                   statius.silvae.part.5.txt                   96
                                      horace.odes.part.4.txt                   95
                                  prudentius.dittochaeon.txt                   94
                              claudian.in_rufinum.part.1.txt                   92
                                          horace.satires.txt                   91
claudian.panegyricus_de_tertio_consulatu_honorii_augusti.txt                   91
                                   statius.silvae.part.4.txt                   89
               claudian.in_consulatum_olybrii_et_probini.txt                   88
                    claudian.de_raptu_proserpinae.part.1.txt                   71
                    claudian.de_raptu_proserpinae.part.3.txt                   69
                             claudian.de_bello_gildonico.txt                   68
                                   statius.silvae.part.3.txt                   48
                                           horace.epodes.txt                   46
                               dracontius.romulea.part.3.txt                   43
                                      horace.odes.part.3.txt                   38
                                      horace.odes.part.2.txt                   34
                               dracontius.romulea.part.1.txt                   29
                         ovid.medicamina_faciei_femineae.txt                   29
                                          ennius.annales.txt                   23
                claudian.de_consulatu_stilichonis.part.1.txt                   22
                                martial.epigrams.part.10.txt                   20
                    claudian.de_raptu_proserpinae.part.2.txt                   18
                               dracontius.romulea.part.2.txt                   13
                                      propertius.elegies.txt                   12
                               dracontius.romulea.part.4.txt                   11
                                         juvenal.satires.txt                   10
                               dracontius.romulea.part.7.txt                    5
                                     catullus.carmina.64.txt                    5
                               dracontius.romulea.part.6.txt                    4
                               dracontius.romulea.part.9.txt                    3
                                martial.epigrams.part.11.txt                    2
                                 catullus.carmina.65_116.txt                    1
                            claudian.in_eutropium.part.1.txt                    1
                claudian.de_consulatu_stilichonis.part.3.txt                    1

In [14]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'epistolography', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.944 ± 0.005
Macro F1: 0.892 ± 0.010

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
                  personal   0.163909  0.008498
           sentence_length   0.124557  0.007418
             interrogative   0.055662  0.005574
           atque_consonant   0.052934  0.004699
                 reflexive   0.052344  0.005876
fraction_sentence_relative   0.047067  0.004248
                cum_clause   0.044250  0.004242
                        si   0.041705  0.004108
                        ut   0.041172  0.003977
                      idem   0.040547  0.003975
                      iste   0.036881  0.002944
             demonstrative   0.034203  0.004097
                     alius   0.031687  0.003493
    relative_clause_length   0.029315  0.002852
                 gerundive   0.026005  0.003647
               conjunction   0.025819  0.003257
               superlative   0.025392  0.002300
               preposition   0.025274  0.003270
                      ipse   0.021139  0.002264
                      quin   0.020212  0.002154
                    quidam   0.017181  0.002307
            o_interjection   0.013692  0.002167
                       dum   0.012825  0.001727
                  antequam   0.007434  0.001029
                  quominus   0.004560  0.000713
                 priusquam   0.004234  0.000892

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
                  personal                     0.056232                    0.003832
           sentence_length                     0.022850                    0.005539
           atque_consonant                     0.002171                    0.001166
                        si                     0.000872                    0.000849
                      iste                     0.000466                    0.000661
                 reflexive                     0.000395                    0.000580
             interrogative                     0.000337                    0.000500
                cum_clause                     0.000267                    0.000316
                      quin                     0.000184                    0.000519
                        ut                     0.000173                    0.000351
fraction_sentence_relative                     0.000135                    0.000337
                      idem                     0.000060                    0.000193
               superlative                     0.000034                    0.000219
    relative_clause_length                     0.000031                    0.000185
            o_interjection                     0.000028                    0.000197
               conjunction                     0.000014                    0.000140
                     alius                     0.000001                    0.000014
                 gerundive                     0.000000                    0.000000
                       dum                     0.000000                    0.000000
             demonstrative                     0.000000                    0.000000
               preposition                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
                    quidam                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                      ipse                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                             File Name  Times Misclassified
                                  augustine.epistulae_41_50.part.5.txt                  100
        cicero.epistulae_ad_familiares.part.14.ad_terentiam_uxorem.txt                  100
                                  augustine.epistulae_51_62.part.6.txt                  100
                                  augustine.epistulae_31_40.part.4.txt                  100
                                                  jerome.epistulae.txt                  100
                 seneca.ad_lucilium_epistulae_morales.part.9.81-90.txt                  100
                                   augustine.epistulae_1_10.part.1.txt                  100
                                  augustine.epistulae_11_20.part.2.txt                  100
                                         cicero.letters_to_quintus.txt                  100
                                  pliny_the_younger.letters.part.8.txt                  100
                                 pliny_the_younger.letters.part.10.txt                   96
              seneca.ad_lucilium_epistulae_morales.part.13.121-124.txt                   94
      cicero.epistulae_ad_familiares.part.13.ad_memmium_et_ceteros.txt                   92
                            seneca_the_elder.controversiae.part.10.txt                   89
cicero.epistulae_ad_familiares.part.8.caeli_epistulae_ad_ciceronem.txt                   76
                                  pliny_the_younger.letters.part.3.txt                   69
                                   cicero.divinatio_in_q_caecilium.txt                   68
                                  augustine.epistulae_21_30.part.3.txt                   66
                                          cicero.letters_to_brutus.txt                   66
                                  pliny_the_younger.letters.part.2.txt                   63
                 seneca.ad_lucilium_epistulae_morales.part.4.31-40.txt                   45
                                  pliny_the_younger.letters.part.5.txt                   45
               seneca.ad_lucilium_epistulae_morales.part.10.91-100.txt                   28
      cicero.epistulae_ad_familiares.part.10.ad_plancum_et_ceteros.txt                   22
                 cicero.epistulae_ad_familiares.part.1.ad_lentulum.txt                   17
                 seneca.ad_lucilium_epistulae_morales.part.8.71-80.txt                   10
                  seneca.ad_lucilium_epistulae_morales.part.1.1-10.txt                   10
                             seneca_the_elder.controversiae.part.8.txt                   10
                                       cicero.pro_q_roscio_comoedo.txt                    8
              seneca.ad_lucilium_epistulae_morales.part.11.101-110.txt                    6
              seneca.ad_lucilium_epistulae_morales.part.12.111-120.txt                    4
                 seneca.ad_lucilium_epistulae_morales.part.7.61-70.txt                    3
                                       seneca.de_beneficiis.part.6.txt                    2
                                  cicero.letters_to_atticus.part.1.txt                    1

In [15]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'historiography', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.949 ± 0.006
Macro F1: 0.924 ± 0.009

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
                      iste   0.181526  0.010314
                 reflexive   0.090939  0.005367
             interrogative   0.080730  0.006407
                        si   0.080057  0.005009
           sentence_length   0.050808  0.004335
                  personal   0.046389  0.004050
                cum_clause   0.045590  0.003151
             demonstrative   0.042508  0.003604
                       dum   0.039806  0.003368
                        ut   0.033907  0.003362
               preposition   0.030735  0.003610
                      idem   0.028286  0.002834
    relative_clause_length   0.027863  0.002530
                 gerundive   0.025424  0.002337
                      ipse   0.020742  0.002379
                 priusquam   0.020302  0.002210
               conjunction   0.020103  0.001981
                    quidam   0.019440  0.002417
               superlative   0.019142  0.001781
           atque_consonant   0.017452  0.001944
                     alius   0.017131  0.001762
            o_interjection   0.015697  0.002333
fraction_sentence_relative   0.015641  0.001651
                  quominus   0.012795  0.001794
                      quin   0.009687  0.001203
                  antequam   0.007301  0.001024

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
                      iste                     0.089621                    0.010018
                 reflexive                     0.010017                    0.002774
                        si                     0.008876                    0.004948
             interrogative                     0.002721                    0.002439
                cum_clause                     0.001115                    0.001251
           sentence_length                     0.000073                    0.000269
                       dum                     0.000069                    0.000247
               superlative                     0.000044                    0.000305
             demonstrative                     0.000029                    0.000218
                  personal                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                    quidam                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
               preposition                     0.000000                    0.000000
                      ipse                     0.000000                    0.000000
            o_interjection                     0.000000                    0.000000
fraction_sentence_relative                     0.000000                    0.000000
                      idem                     0.000000                    0.000000
                 gerundive                     0.000000                    0.000000
               conjunction                     0.000000                    0.000000
           atque_consonant                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                     alius                     0.000000                    0.000000
    relative_clause_length                     0.000000                    0.000000
                        ut                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                            File Name  Times Misclassified
                                                 jerome.epistulae.txt                  100
                                                sallust.histories.txt                  100
                                                   cicero.timaeus.txt                  100
                           florus.epitome_bellorum_omnium_annorum.txt                  100
               valerius_maximus.facta_et_dicta_memorabilia.part.4.txt                  100
               valerius_maximus.facta_et_dicta_memorabilia.part.5.txt                  100
scriptores_historiae_augustae.historia_augusta.part.4.books_16-21.txt                  100
                                                      nepos.vitae.txt                   99
                                           tacitus.annales.part.5.txt                   99
 scriptores_historiae_augustae.historia_augusta.part.2.books_6-10.txt                   97
scriptores_historiae_augustae.historia_augusta.part.3.books_11-15.txt                   90
                                   cicero.cum_populo_gratias_egit.txt                   89
                          caesar_augustus.res_gestae_divi_augusti.txt                   88
                                         tacitus.historiae.part.5.txt                   83
  scriptores_historiae_augustae.historia_augusta.part.1.books_1-5.txt                   72
                          curtius_rufus.historiae_alexandri_magni.txt                   66
                                           tacitus.annales.part.4.txt                   47
               valerius_maximus.facta_et_dicta_memorabilia.part.9.txt                   30
                          livy.ab_urbe_condita.part.4.books_41-45.txt                   27
                                          tacitus.annales.part.16.txt                   25
               valerius_maximus.facta_et_dicta_memorabilia.part.8.txt                   23
                                          tacitus.annales.part.11.txt                   21
                                                 tacitus.agricola.txt                   18
                                   caesar.de_bello_gallico.part.3.txt                   17
                                       seneca_the_elder.fragmenta.txt                   17
                                      gellius.attic_nights.part.8.txt                   17
               valerius_maximus.facta_et_dicta_memorabilia.part.6.txt                   15
                                                 sallust.jugurtha.txt                   10
                                 vitruvius.de_architectura.part.4.txt                   10
                                           tacitus.annales.part.1.txt                    8
                                           tacitus.annales.part.3.txt                    7
                                                 sallust.catilina.txt                    6
                             quintilian_pseudo.major_declamations.txt                    6
                                        cicero.philippicae.part.9.txt                    5
                                 cicero.de_optimo_genere_oratorum.txt                    5
                                 vitruvius.de_architectura.part.3.txt                    5
            pliny_the_elder.naturalis_historia.part.4.books_16-20.txt                    4
                                 vitruvius.de_architectura.part.7.txt                    4
                                 vitruvius.de_architectura.part.2.txt                    4
                                 vitruvius.de_architectura.part.5.txt                    4
               valerius_maximus.facta_et_dicta_memorabilia.part.2.txt                    4
                                         tacitus.historiae.part.4.txt                    3
                          suetonius.de_vita_caesarum.part.7.galba.txt                    1
                      suetonius.de_vita_caesarum.part.9.vitellius.txt                    1
                      tacitus.de_origine_et_situ_germanorum_liber.txt                    1
                           suetonius.de_vita_caesarum.part.8.otho.txt                    1
                         suetonius.de_vita_caesarum.part.11.titus.txt                    1
                          livy.ab_urbe_condita.part.3.books_31-40.txt                    1
                       suetonius.de_vita_caesarum.part.2.augustus.txt                    1

In [16]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'oratory', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.922 ± 0.006
Macro F1: 0.843 ± 0.015

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
             interrogative   0.143778  0.007726
               conjunction   0.092479  0.006489
                     alius   0.076899  0.005477
                      iste   0.063263  0.004900
                    quidam   0.054355  0.004607
    relative_clause_length   0.052347  0.003982
                       dum   0.049976  0.004573
               superlative   0.048082  0.003824
               preposition   0.040846  0.004110
           sentence_length   0.038069  0.002977
            o_interjection   0.036244  0.003248
fraction_sentence_relative   0.033408  0.002821
                  personal   0.031627  0.002436
                        si   0.028116  0.002775
                 gerundive   0.026220  0.002548
             demonstrative   0.025730  0.002466
                cum_clause   0.025562  0.002612
                      idem   0.025259  0.002570
                      ipse   0.021702  0.002093
                        ut   0.020476  0.001850
                 reflexive   0.018048  0.002028
           atque_consonant   0.017451  0.001716
                      quin   0.013843  0.001344
                  antequam   0.005659  0.000895
                  quominus   0.005439  0.000875
                 priusquam   0.005123  0.001138

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
             interrogative                     0.052656                    0.010163
               conjunction                     0.018066                    0.007025
                       dum                     0.006164                    0.001826
                     alius                     0.004438                    0.002579
    relative_clause_length                     0.002935                    0.001366
               superlative                     0.002753                    0.001556
                      iste                     0.002663                    0.001090
                      quin                     0.002604                    0.000235
                    quidam                     0.001768                    0.001422
            o_interjection                     0.001666                    0.001662
           sentence_length                     0.001316                    0.001134
               preposition                     0.000285                    0.000755
                      idem                     0.000285                    0.000632
                 priusquam                     0.000163                    0.000603
                  personal                     0.000084                    0.000376
                        ut                     0.000017                    0.000089
fraction_sentence_relative                     0.000000                    0.000000
                 gerundive                     0.000000                    0.000000
             demonstrative                     0.000000                    0.000000
                cum_clause                     0.000000                    0.000000
           atque_consonant                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
                 reflexive                     0.000000                    0.000000
                        si                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                      ipse                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                     File Name  Times Misclassified
                         cicero.de_provinciis_consularibus.txt                  100
                           cicero.divinatio_in_q_caecilium.txt                  100
                      quintilian_pseudo.major_declamations.txt                  100
                            cicero.cum_populo_gratias_egit.txt                  100
                                cicero.philippicae.part.13.txt                  100
                                seneca_the_elder.suasoriae.txt                  100
                                          apuleius.florida.txt                  100
                       cicero.divinatio_in_c_verrem.part.1.txt                  100
                                          cicero.pro_balbo.txt                  100
cicero.epistulae_ad_familiares.part.14.ad_terentiam_uxorem.txt                  100
                               cicero.de_imperio_cn_pompei.txt                  100
                                         cicero.pro_murena.txt                  100
                                seneca_the_elder.fragmenta.txt                   98
                                 cicero.philippicae.part.5.txt                   98
                                     cicero.pro_a_cluentio.txt                   95
                                         apuleius.apologia.txt                   93
                                      cicero.pro_a_caecina.txt                   93
                                       cicero.pro_m_caelio.txt                   91
                                 cicero.philippicae.part.9.txt                   90
                             cicero.post_reditum_in_senatu.txt                   81
                                cicero.pro_publio_quinctio.txt                   79
                               gellius.attic_nights.part.8.txt                   75
                                       cicero.pro_marcello.txt                   74
                                         cicero.pro_archia.txt                   72
                                 cicero.philippicae.part.4.txt                   64
                                       cicero.in_catilinam.txt                   61
                               cicero_pseudo.in_sallustium.txt                   53
                                 cicero.philippicae.part.6.txt                   43
                                          jerome.epistulae.txt                   43
                                     seneca.de_providentia.txt                   25
                                        cicero.pro_fonteio.txt                   25
                     seneca_the_elder.controversiae.part.8.txt                   23
                                         cicero.pro_sestio.txt                   22
                                          cicero.pro_sulla.txt                   21
                                        cicero.pro_ligario.txt                   20
                                       petronius.satyricon.txt                   18
                      cicero.de_lege_agraria_contra_rullum.txt                   16
                                    tacitus.annales.part.5.txt                   15
                     seneca_the_elder.controversiae.part.1.txt                   14
                              cicero.pro_c_rabirio_postumo.txt                   13
                             cicero.de_haruspicum_responso.txt                   10
                    seneca_the_elder.controversiae.part.10.txt                   10
                                 cicero.letters_to_quintus.txt                    7
                   seneca_the_elder.excerpta_controversiae.txt                    6
                                cicero.philippicae.part.11.txt                    6
         seneca.ad_lucilium_epistulae_morales.part.9.81-90.txt                    6
                       cicero.divinatio_in_c_verrem.part.4.txt                    4
                     seneca_the_elder.controversiae.part.7.txt                    4
                         cicero.letters_to_atticus.part.13.txt                    3
                                            seneca.de_otio.txt                    2
                          cicero.de_optimo_genere_oratorum.txt                    1
                       cicero.divinatio_in_c_verrem.part.3.txt                    1
                     seneca_the_elder.controversiae.part.2.txt                    1
                    cicero.tusculanae_disputationes.part.1.txt                    1
                                         cicero.pro_milone.txt                    1
                                  cicero.pro_rege_deiotaro.txt                    1

In [17]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'philosophy', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.903 ± 0.007
Macro F1: 0.737 ± 0.025

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
    relative_clause_length   0.083974  0.004251
             interrogative   0.081337  0.004440
fraction_sentence_relative   0.077170  0.004307
               superlative   0.072312  0.004115
           sentence_length   0.058933  0.004556
                      iste   0.053471  0.003634
                  personal   0.044359  0.003405
                     alius   0.044254  0.003531
               preposition   0.043123  0.003720
                        si   0.042337  0.003349
                 reflexive   0.040922  0.003672
                    quidam   0.040204  0.003123
                      ipse   0.032704  0.002551
               conjunction   0.031982  0.002606
             demonstrative   0.031967  0.003053
                      idem   0.027687  0.002352
                        ut   0.027319  0.002548
                 gerundive   0.026569  0.002638
                       dum   0.026462  0.002224
           atque_consonant   0.024641  0.002548
                cum_clause   0.023522  0.002359
                      quin   0.016388  0.001717
            o_interjection   0.015720  0.001928
                  antequam   0.013504  0.001654
                 priusquam   0.011054  0.001420
                  quominus   0.008087  0.001020

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
             interrogative                     0.038910                    0.008384
    relative_clause_length                     0.017933                    0.004830
               superlative                     0.010511                    0.002703
fraction_sentence_relative                     0.008355                    0.001790
                      iste                     0.006971                    0.003138
                     alius                     0.001739                    0.001121
                    quidam                     0.000690                    0.000856
                      idem                     0.000517                    0.001016
           sentence_length                     0.000160                    0.000312
                cum_clause                     0.000135                    0.000467
                  personal                     0.000125                    0.000299
                      ipse                     0.000105                    0.000359
                        si                     0.000060                    0.000254
                 reflexive                     0.000056                    0.000242
               preposition                     0.000053                    0.000314
                       dum                     0.000037                    0.000268
             demonstrative                     0.000029                    0.000167
           atque_consonant                     0.000027                    0.000168
               conjunction                     0.000006                    0.000056
                  antequam                     0.000003                    0.000028
                        ut                     0.000001                    0.000014
                 gerundive                     0.000000                    0.000000
            o_interjection                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                      File Name  Times Misclassified
                         cicero.de_amicitia.txt                  100
                  cicero.de_officiis.part.1.txt                  100
      cicero.paradoxa_stoicorum_ad_m_brutum.txt                  100
                             cicero.timaeus.txt                  100
                           cicero.academica.txt                  100
           cicero.de_optimo_genere_oratorum.txt                  100
                        cicero.de_senectute.txt                  100
                              cicero.topica.txt                  100
                             seneca.de_otio.txt                  100
                      seneca.de_providentia.txt                  100
                  tertullian.de_spectaculis.txt                  100
cicero.de_finibus_bonorum_et_malorum.part.2.txt                  100
             cicero.de_natura_deorum.part.2.txt                  100
             cicero.de_natura_deorum.part.3.txt                  100
                seneca.de_beneficiis.part.1.txt                  100
             tacitus.dialogus_de_oratoribus.txt                  100
              cicero.de_haruspicum_responso.txt                  100
                  cicero.de_officiis.part.2.txt                  100
                       seneca.de_constantia.txt                  100
                              seneca.de_ira.txt                  100
                    tertullian.apologeticum.txt                  100
                            cicero.lucullus.txt                   99
             cicero.de_natura_deorum.part.1.txt                   98
                             cicero.de_fato.txt                   97
                              cicero.brutus.txt                   94
                              cicero.orator.txt                   89
     cicero.tusculanae_disputationes.part.1.txt                   84
     cicero.tusculanae_disputationes.part.2.txt                   81
                      cicero.de_divinatione.txt                   76
         seneca.de_consolatione_ad_polybium.txt                   74
     cicero.tusculanae_disputationes.part.5.txt                   70
cicero.de_finibus_bonorum_et_malorum.part.1.txt                   62
                        cicero.de_republica.txt                   61
cicero.de_finibus_bonorum_et_malorum.part.5.txt                   58
                   cicero.de_oratore.part.3.txt                   55
          seneca.de_consolatione_ad_marciam.txt                   46
                  seneca.de_brevitate_vitae.txt                   35
             marcus_mincuius_felix.octavius.txt                   35
             seneca.de_tranquillitate_animi.txt                   26
                  cicero.de_officiis.part.3.txt                   21
                seneca.de_beneficiis.part.2.txt                   18
          seneca.de_consolatione_ad_helviam.txt                   12
cicero.de_finibus_bonorum_et_malorum.part.3.txt                   12
                   cicero.de_oratore.part.2.txt                   11
                macrobius.saturnalia.part.1.txt                   10
                        seneca.de_clementia.txt                   10
                   cicero.de_oratore.part.1.txt                    4
      quintilian.institutio_oratoria.part.9.txt                    4
                seneca.de_beneficiis.part.7.txt                    3
           augustine.epistulae_41_50.part.5.txt                    3
           augustine.epistulae_51_62.part.6.txt                    3
                seneca.de_beneficiis.part.6.txt                    3
     quintilian.institutio_oratoria.part.11.txt                    1
                seneca.de_beneficiis.part.5.txt                    1
                macrobius.saturnalia.part.7.txt                    1

In [18]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'technical treatise', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.963 ± 0.005
Macro F1: 0.897 ± 0.019

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
                  personal   0.149879  0.008941
                 gerundive   0.082896  0.006087
                        si   0.060441  0.005994
               conjunction   0.060068  0.005707
                 reflexive   0.054993  0.005483
                      iste   0.054660  0.005681
             interrogative   0.052140  0.004723
               preposition   0.049820  0.005555
                cum_clause   0.045113  0.004864
                    quidam   0.044720  0.004056
    relative_clause_length   0.041487  0.004386
                      ipse   0.036077  0.004435
             demonstrative   0.035492  0.004575
                      idem   0.029543  0.003431
           sentence_length   0.026071  0.003388
                     alius   0.025265  0.003484
                        ut   0.025211  0.003393
               superlative   0.023997  0.003141
fraction_sentence_relative   0.023464  0.002619
           atque_consonant   0.016887  0.002590
                  antequam   0.016520  0.002029
                      quin   0.013424  0.002141
                       dum   0.011249  0.001671
                 priusquam   0.009547  0.001588
            o_interjection   0.006483  0.001485
                  quominus   0.004552  0.000993

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
                  personal                     0.024160                    0.007517
                 gerundive                     0.005327                    0.002504
fraction_sentence_relative                     0.003206                    0.001056
               conjunction                     0.001765                    0.001219
                      iste                     0.001551                    0.001338
    relative_clause_length                     0.001417                    0.000989
               superlative                     0.000962                    0.001160
             interrogative                     0.000628                    0.000953
                 reflexive                     0.000469                    0.000633
                    quidam                     0.000437                    0.000924
           atque_consonant                     0.000239                    0.000611
                cum_clause                     0.000190                    0.000400
                        si                     0.000129                    0.000324
                      idem                     0.000121                    0.000417
                      ipse                     0.000017                    0.000142
                        ut                     0.000014                    0.000085
           sentence_length                     0.000010                    0.000098
            o_interjection                     0.000000                    0.000000
               preposition                     0.000000                    0.000000
                 priusquam                     0.000000                    0.000000
                       dum                     0.000000                    0.000000
                      quin                     0.000000                    0.000000
                  quominus                     0.000000                    0.000000
             demonstrative                     0.000000                    0.000000
                  antequam                     0.000000                    0.000000
                     alius                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                 File Name  Times Misclassified
             cicero.de_officiis.part.1.txt                  100
             celsus.de_medicina.part.1.txt                  100
         cicero.de_partitione_oratoria.txt                  100
        columella.de_re_rustica.part.1.txt                  100
      vitruvius.de_architectura.part.7.txt                  100
        columella.de_re_rustica.part.5.txt                  100
        q_cicero.on_running_for_consul.txt                  100
 quintilian.institutio_oratoria.part.9.txt                  100
      vitruvius.de_architectura.part.4.txt                  100
        columella.de_re_rustica.part.3.txt                  100
           cicero.de_inventione.part.2.txt                   65
      vitruvius.de_architectura.part.3.txt                   38
      vitruvius.de_architectura.part.2.txt                   37
 quintilian.institutio_oratoria.part.7.txt                   36
        columella.de_re_rustica.part.9.txt                   27
        columella.de_re_rustica.part.7.txt                   23
quintilian.institutio_oratoria.part.11.txt                   16
 quintilian.institutio_oratoria.part.1.txt                   11
      vitruvius.de_architectura.part.9.txt                   10
     vitruvius.de_architectura.part.10.txt                   10
 quintilian.institutio_oratoria.part.8.txt                    9
 quintilian.institutio_oratoria.part.5.txt                    7
        columella.de_re_rustica.part.4.txt                    7
      vitruvius.de_architectura.part.6.txt                    7
           cicero.de_inventione.part.1.txt                    6
      vitruvius.de_architectura.part.5.txt                    5
quintilian.institutio_oratoria.part.10.txt                    4
quintilian.institutio_oratoria.part.12.txt                    2
      vitruvius.de_architectura.part.8.txt                    1
      vitruvius.de_architectura.part.1.txt                    1

In [19]:
train_evaluate_genre_100times_with_misclassified(df_prose, 'miscellaneous', 42, 200)

=== Results Over 100 Trials (Each w/ 5-fold CV) ===
Accuracy: 0.956 ± 0.005
Macro F1: 0.885 ± 0.016

=== Gini Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Gini  Std Gini
           atque_consonant   0.117209  0.008351
                      iste   0.098351  0.007299
                        ut   0.072846  0.006097
                        si   0.063969  0.004860
             interrogative   0.062790  0.006057
                    quidam   0.052844  0.004969
                      idem   0.046878  0.004533
                  personal   0.044159  0.004192
               conjunction   0.040026  0.003773
fraction_sentence_relative   0.036938  0.003394
               superlative   0.034955  0.003226
           sentence_length   0.033385  0.003470
                     alius   0.030348  0.002913
                      ipse   0.029256  0.003403
               preposition   0.027934  0.003342
    relative_clause_length   0.025747  0.002749
                 gerundive   0.024804  0.002883
                 reflexive   0.024182  0.002648
             demonstrative   0.023524  0.002725
                cum_clause   0.022995  0.002647
                       dum   0.022415  0.002507
            o_interjection   0.017335  0.001837
                  quominus   0.016497  0.002225
                  antequam   0.010798  0.001593
                      quin   0.010633  0.001569
                 priusquam   0.009184  0.001428

=== Permutation Importances (Mean ± Std over 100 Trials) ===
              Feature Name  Mean Permutation Importance  Std Permutation Importance
           atque_consonant                     0.025747                    0.005551
                        ut                     0.014369                    0.005892
                        si                     0.009108                    0.001839
                      iste                     0.003642                    0.002527
                       dum                     0.002490                    0.000754
fraction_sentence_relative                     0.002219                    0.001772
            o_interjection                     0.002021                    0.001639
                cum_clause                     0.001864                    0.001505
                  personal                     0.000798                    0.000902
               superlative                     0.000708                    0.001077
                    quidam                     0.000681                    0.000532
                      idem                     0.000617                    0.001068
    relative_clause_length                     0.000611                    0.000975
             interrogative                     0.000542                    0.000863
                 gerundive                     0.000472                    0.000942
                     alius                     0.000372                    0.000724
               conjunction                     0.000341                    0.000789
                      ipse                     0.000340                    0.000752
                 priusquam                     0.000316                    0.000763
                  quominus                     0.000233                    0.000508
               preposition                     0.000202                    0.000695
                 reflexive                     0.000087                    0.000276
             demonstrative                     0.000086                    0.000321
                  antequam                     0.000072                    0.000307
           sentence_length                     0.000041                    0.000219
                      quin                     0.000000                    0.000000

=== Misclassified Texts Over 100 Trials ===
                                                File Name  Times Misclassified
                                  petronius.satyricon.txt                  100
                          gellius.attic_nights.part.8.txt                  100
                          macrobius.saturnalia.part.1.txt                  100
                          macrobius.saturnalia.part.5.txt                  100
                          macrobius.saturnalia.part.2.txt                  100
                          macrobius.saturnalia.part.3.txt                  100
                          macrobius.saturnalia.part.6.txt                  100
                          macrobius.saturnalia.part.4.txt                  100
                          macrobius.saturnalia.part.7.txt                  100
                        apuleius.metamorphoses.part.1.txt                   95
                         gellius.attic_nights.part.15.txt                   94
                          gellius.attic_nights.part.1.txt                   93
                         gellius.attic_nights.part.11.txt                   69
                           seneca_the_elder.fragmenta.txt                   64
  pliny_the_elder.naturalis_historia.part.1.books_1-5.txt                   56
                       apuleius.metamorphoses.part.11.txt                   43
                         gellius.attic_nights.part.13.txt                   31
                 quintilian_pseudo.major_declamations.txt                   23
                          gellius.attic_nights.part.4.txt                   16
                          gellius.attic_nights.part.7.txt                   10
                         gellius.attic_nights.part.20.txt                   10
                        apuleius.metamorphoses.part.9.txt                    8
                          gellius.attic_nights.part.6.txt                    8
                          gellius.attic_nights.part.2.txt                    5
                         gellius.attic_nights.part.14.txt                    4
                        apuleius.metamorphoses.part.6.txt                    3
                          gellius.attic_nights.part.5.txt                    3
                         gellius.attic_nights.part.17.txt                    3
                                     cicero.academica.txt                    3
                                     jerome.epistulae.txt                    2
pliny_the_elder.naturalis_historia.part.7.books_31-37.txt                    2
 pliny_the_elder.naturalis_historia.part.2.books_6-10.txt                    2
                          gellius.attic_nights.part.3.txt                    1
               livy.ab_urbe_condita.part.1.books_1-10.txt                    1
              livy.ab_urbe_condita.part.2.books_21-30.txt                    1
                       apuleius.metamorphoses.part.10.txt                    1
                        apuleius.metamorphoses.part.2.txt                    1
                        apuleius.metamorphoses.part.8.txt                    1

In [47]:
def repeated_one_vs_rest_classification(
    df: pd.DataFrame,
    target_genre: str,
    n_repeats: int = 5,
    n_estimators: int = 100,
    random_state: int = 42
):
    """
    Perform one-vs.-rest classification for a given genre using a Random Forest.
    
    Parameters
    ----------
    df : pd.DataFrame
        DataFrame containing columns:
            - "Genre": the class label.
            - "File Name": the unique identifier for each text/document.
            - Numerical feature columns from "sentence_length" to "ut" (26 columns).
    target_genre : str
        The genre for which we do one-vs.-rest classification.
    n_repeats : int, optional
        Number of times to repeat the entire 5-fold stratified cross-validation. 
        (Default is 5)
    n_estimators : int, optional
        Number of trees in the random forest. (Default is 100)
    random_state : int, optional
        Random seed for reproducibility. (Default is 42)
    
    Returns
    -------
    results : dict
        Dictionary containing the following keys:
            - "accuracy_mean": float
            - "accuracy_std": float
            - "f1_mean": float
            - "f1_std": float
            - "misclass_fraction_df": pd.DataFrame 
                columns = ["File Name", "Fraction of Misclassifications"]
            - "gini_importance_df": pd.DataFrame 
                columns = ["Feature Name", "Mean Gini", "SD Gini"]
            - "perm_importance_df": pd.DataFrame 
                columns = ["Feature Name", "Mean Permutation Importance", "SD Permutation Importance"]
    """
    
    # -----------------------------
    # 1) Prepare data
    # -----------------------------
    # Identify feature columns (assuming they are from "sentence_length" to "ut")
    # If you prefer an explicit list, you can replace this part with a known list of columns.
    feature_cols = df.loc[:, "sentence_length":"ut"].columns.tolist()
    
    # Binarize the target: 1 if Genre == target_genre, else 0
    df = df.copy()  # To avoid modifying the original DataFrame
    df["target"] = (df["Genre"] == target_genre).astype(int)
    
    X = df[feature_cols].values
    y = df["target"].values
    file_names = df["File Name"].values
    
    # -----------------------------
    # 2) Set up repeated stratified 5-fold cross-validation
    # -----------------------------
    rskf = RepeatedStratifiedKFold(
        n_splits=5, 
        n_repeats=n_repeats, 
        random_state=random_state
    )
    
    # -----------------------------
    # 3) Storage for metrics and importances
    # -----------------------------
    accuracies = []
    f1_scores = []
    
    # Track misclassifications per document
    # key: file_name -> [times_in_test_set, times_misclassified]
    misclass_dict = {}
    for fn in file_names:
        misclass_dict[fn] = [0, 0]

    # For storing Gini importances: one list per fold
    gini_importances_list = []
    # For storing Permutation importances: one list per fold
    perm_importances_list = []
    
    # -----------------------------
    # 4) Cross-validation loop
    # -----------------------------
    for train_idx, test_idx in rskf.split(X, y):
        # Split data
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]
        fn_test = file_names[test_idx]
        
        # Random Forest classifier
        rf = RandomForestClassifier(
            n_estimators=n_estimators, 
            random_state=random_state
        )
        rf.fit(X_train, y_train)
        
        # Predictions
        y_pred = rf.predict(X_test)
        
        # Accuracy, Macro F1
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average='macro')
        
        accuracies.append(acc)
        f1_scores.append(f1)
        
        # Track misclassifications for each doc
        for i, pred in enumerate(y_pred):
            true_label = y_test[i]
            misclass_dict[fn_test[i]][0] += 1  # tested once more
            if pred != true_label:
                misclass_dict[fn_test[i]][1] += 1
        
        # Gini feature importances
        gini_importances_list.append(rf.feature_importances_)
        
        # Permutation importance
        perm_imp = permutation_importance(
            rf, X_test, y_test, 
            n_repeats=10, 
            random_state=random_state, 
            n_jobs=-1
        )
        perm_importances_list.append(perm_imp.importances_mean)
    
    # -----------------------------
    # 5) Aggregate results
    # -----------------------------
    # Accuracy and F1
    accuracy_mean = np.mean(accuracies)
    accuracy_std = np.std(accuracies)
    f1_mean = np.mean(f1_scores)
    f1_std = np.std(f1_scores)
    
    # -----------------------------
    # 6) Fraction of times each doc is misclassified
    # -----------------------------
    misclass_fractions = []
    for fn, (times_tested, times_miscl) in misclass_dict.items():
        frac_miscl = times_miscl / times_tested if times_tested > 0 else 0.0
        misclass_fractions.append((fn, frac_miscl))
    misclass_fraction_df = pd.DataFrame(
        misclass_fractions, 
        columns=["File Name", "Fraction of Misclassifications"]
    )
    
    # -----------------------------
    # 7) Mean and std of Gini importances
    # -----------------------------
    gini_array = np.array(gini_importances_list)  # shape: (n_folds_total, n_features)
    gini_means = np.mean(gini_array, axis=0)
    gini_stds = np.std(gini_array, axis=0)
    
    gini_importance_df = pd.DataFrame({
        "Feature Name": feature_cols,
        "Mean Gini": gini_means,
        "SD Gini": gini_stds
    }).sort_values("Mean Gini", ascending=False).reset_index(drop=True)
    
    # -----------------------------
    # 8) Mean and std of permutation importances
    # -----------------------------
    perm_array = np.array(perm_importances_list)  # shape: (n_folds_total, n_features)
    perm_means = np.mean(perm_array, axis=0)
    perm_stds = np.std(perm_array, axis=0)
    
    perm_importance_df = pd.DataFrame({
        "Feature Name": feature_cols,
        "Mean Permutation Importance": perm_means,
        "SD Permutation Importance": perm_stds
    }).sort_values("Mean Permutation Importance", ascending=False).reset_index(drop=True)
    
    # -----------------------------
    # 9) Prepare final output
    # -----------------------------
    results = {
        "accuracy_mean": accuracy_mean,
        "accuracy_std": accuracy_std,
        "f1_mean": f1_mean,
        "f1_std": f1_std,
        "misclass_fraction_df": misclass_fraction_df,
        "gini_importance_df": gini_importance_df,
        "perm_importance_df": perm_importance_df
    }
    
    return results

In [48]:
# Example usage:
df = df_verse
results = repeated_one_vs_rest_classification(df, target_genre="Epic", n_repeats=5)

# # Access results
print("Mean accuracy:", results["accuracy_mean"])
print("Std accuracy:", results["accuracy_std"])
print("Mean F1 (macro):", results["f1_mean"])
print("Std F1 (macro):", results["f1_std"])
# 
# # Misclassification fraction per document
print(results["misclass_fraction_df"])
# 
# # Feature importances
print(results["gini_importance_df"])
print(results["perm_importance_df"])

Mean accuracy: 1.0
Std accuracy: 0.0
Mean F1 (macro): 1.0
Std F1 (macro): 0.0
                     File Name  Fraction of Misclassifications
0        plautus.amphitruo.txt                             0.0
1         plautus.asinaria.txt                             0.0
2        plautus.aulularia.txt                             0.0
3        plautus.bacchides.txt                             0.0
4          plautus.captivi.txt                             0.0
..                         ...                             ...
229  statius.silvae.part.2.txt                             0.0
230  statius.silvae.part.3.txt                             0.0
231  statius.silvae.part.4.txt                             0.0
232  statius.silvae.part.5.txt                             0.0
233        vergil.eclogues.txt                             0.0

[234 rows x 2 columns]
                  Feature Name  Mean Gini  SD Gini
0              sentence_length        0.0      0.0
1   fraction_sentence_relative        0.0      0.0
2                  superlative        0.0      0.0
3                           si        0.0      0.0
4                    reflexive        0.0      0.0
5                     quominus        0.0      0.0
6                         quin        0.0      0.0
7                       quidam        0.0      0.0
8                    priusquam        0.0      0.0
9                  preposition        0.0      0.0
10                    personal        0.0      0.0
11              o_interjection        0.0      0.0
12                        iste        0.0      0.0
13                        ipse        0.0      0.0
14               interrogative        0.0      0.0
15                        idem        0.0      0.0
16                   gerundive        0.0      0.0
17                         dum        0.0      0.0
18               demonstrative        0.0      0.0
19                  cum_clause        0.0      0.0
20                 conjunction        0.0      0.0
21             atque_consonant        0.0      0.0
22                    antequam        0.0      0.0
23                       alius        0.0      0.0
24      relative_clause_length        0.0      0.0
25                          ut        0.0      0.0
                  Feature Name  Mean Permutation Importance  \
0              sentence_length                          0.0
1   fraction_sentence_relative                          0.0
2                  superlative                          0.0
3                           si                          0.0
4                    reflexive                          0.0
5                     quominus                          0.0
6                         quin                          0.0
7                       quidam                          0.0
8                    priusquam                          0.0
9                  preposition                          0.0
10                    personal                          0.0
11              o_interjection                          0.0
12                        iste                          0.0
13                        ipse                          0.0
14               interrogative                          0.0
15                        idem                          0.0
16                   gerundive                          0.0
17                         dum                          0.0
18               demonstrative                          0.0
19                  cum_clause                          0.0
20                 conjunction                          0.0
21             atque_consonant                          0.0
22                    antequam                          0.0
23                       alius                          0.0
24      relative_clause_length                          0.0
25                          ut                          0.0

    SD Permutation Importance
0                         0.0
1                         0.0
2                         0.0
3                         0.0
4                         0.0
5                         0.0
6                         0.0
7                         0.0
8                         0.0
9                         0.0
10                        0.0
11                        0.0
12                        0.0
13                        0.0
14                        0.0
15                        0.0
16                        0.0
17                        0.0
18                        0.0
19                        0.0
20                        0.0
21                        0.0
22                        0.0
23                        0.0
24                        0.0
25                        0.0

In [13]:
# epic dataset

df_epic = df_verse.loc[(df_verse['Genre'] == 'epic')]
df_epic = df_epic.loc[df_epic['Author'].isin(['Catullus', 'Ovid', 'Lucan', 'Statius', 'Valerius Flaccus', 'Vergil'])]

df_silius = df_verse.loc[(df_verse['Author'] == 'Silius Italicus')]
df_manilius = df_verse.loc[(df_verse['Author'] == 'Manilius')]
df_lucretius = df_verse.loc[(df_verse['Author'] == 'Lucretius')]

df_epic = pd.concat([df_silius, df_manilius, df_lucretius, df_epic])
df_epic.to_csv('stylometry_data_epic.csv')
df_epic

Empty DataFrame
Columns: [Author, Work, Genre, File Name, word_count, sentence_count, sentence_length, fraction_sentence_relative, relative_clause_length, alius, antequam, atque_consonant, conjunction, cum_clause, demonstrative, dum, gerundive, idem, interrogative, ipse, iste, o_interjection, personal, preposition, priusquam, quidam, quin, quominus, reflexive, si, superlative, ut]
Index: []

[0 rows x 32 columns]

In [14]:
# satire dataset

df_epic = df_verse.loc[(df_verse['Genre'] == 'epic')]
df_epic = df_epic.loc[df_epic['Author'].isin(['Catullus', 'Vergil', 'Ovid', 'Lucan', 'Silius Italicus', 'Statius', 'Valerius Flaccus'])]
df_epic = df_epic[df_epic['Work'] != 'Georgics']
df_satire = df_verse.loc[(df_verse['Work'] == 'Satires')]
df_epic_satire = pd.concat([df_epic,df_satire])

df_epic_satire.to_csv('stylometry_data_satire.csv')
df_epic_satire

Empty DataFrame
Columns: [Author, Work, Genre, File Name, word_count, sentence_count, sentence_length, fraction_sentence_relative, relative_clause_length, alius, antequam, atque_consonant, conjunction, cum_clause, demonstrative, dum, gerundive, idem, interrogative, ipse, iste, o_interjection, personal, preposition, priusquam, quidam, quin, quominus, reflexive, si, superlative, ut]
Index: []

[0 rows x 32 columns]

In [76]:
# custom sorting function
def sort_by_first_and_third_word(df, column_name):
    """Sorts a DataFrame alphabetically by the first and third word in a column."""

    df['first_word'] = df[column_name].str.split().str[0]
    df['third_word'] = df[column_name].str.split().str[2]
    df.sort_values(by=['first_word', 'third_word'], inplace=True)
    df.drop(['first_word', 'third_word'], axis=1, inplace=True)
    return df

# Example usage:
df = pd.DataFrame({'text_column': ['the quick brown fox', 'jumps over the lazy dog', 'a quick brown fox']})
df = sort_by_first_and_third_word(df, 'text_column')
#print(df)

In [80]:
# mortal and divine speech

df_mortal_divine = pd.read_csv('20241125_053108-normed.csv')
df_mortal_divine = df_mortal_divine.rename(columns={'Unnamed: 0': 'File Name'}) 
df_mortal_divine = df_mortal_divine.sort_values(by='File Name')
df_mortal_divine = sort_by_first_and_third_word(df_mortal_divine, 'File Name')
df_mortal_divine_base = df_mortal_divine[df_mortal_divine['File Name'] != 'aeneid 12 divine speech no juturna.txt']
df_mortal_divine_base.to_csv('mortal_divine_base_speech.csv')
df_mortal_divine_base

,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,antequam,atque_consonant,conjunction,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,aeneid 1 divine speech.txt,1414,64,19.234375,0.328125,5.560000,0.000707,0.0,0.000000,0.089109,...,0.027581,0.027581,0.000000,0.0,0.000707,0.0,0.002122,0.001414,0.001414,0.002829
2,aeneid 10 divine speech.txt,1142,70,14.228571,0.142857,4.538462,0.000876,0.0,0.001751,0.095447,...,0.017513,0.024518,0.000000,0.0,0.002627,0.0,0.000876,0.008757,0.000876,0.003503
4,aeneid 11 divine speech.txt,539,27,17.333333,0.074074,5.666667,0.001855,0.0,0.000000,0.068646,...,0.014842,0.044527,0.000000,0.0,0.000000,0.0,0.007421,0.000000,0.000000,0.003711
7,aeneid 12 divine speech.txt,709,49,12.653061,0.183673,4.545455,0.001410,0.0,0.000000,0.084626,...,0.033850,0.033850,0.000000,0.0,0.000000,0.0,0.001410,0.004231,0.001410,0.005642
11,aeneid 4 divine speech.txt,554,37,13.027027,0.216216,5.625000,0.000000,0.0,0.000000,0.108303,...,0.034296,0.021661,0.000000,0.0,0.001805,0.0,0.000000,0.012635,0.000000,0.000000
15,aeneid 7 divine speech.txt,626,35,15.628571,0.200000,6.300000,0.000000,0.0,0.004792,0.087859,...,0.031949,0.035144,0.000000,0.0,0.003195,0.0,0.000000,0.007987,0.000000,0.001597
17,aeneid 8 divine speech.txt,465,26,15.576923,0.307692,6.000000,0.002151,0.0,0.000000,0.073118,...,0.038710,0.025806,0.000000,0.0,0.000000,0.0,0.000000,0.004301,0.004301,0.002151
1,aeneid 1 mortal speech.txt,1178,65,15.846154,0.215385,4.562500,0.000000,0.0,0.000849,0.094228,...,0.029711,0.032258,0.000000,0.0,0.000000,0.0,0.001698,0.010187,0.000849,0.000849
3,aeneid 10 mortal speech.txt,1012,79,11.151899,0.202532,4.647059,0.000000,0.0,0.000000,0.074111,...,0.041502,0.028656,0.000000,0.0,0.000000,0.0,0.000988,0.003953,0.002964,0.000988
5,aeneid 11 mortal speech.txt,2628,145,15.827586,0.275862,5.936170,0.001903,0.0,0.000000,0.095129,...,0.028539,0.031963,0.000000,0.0,0.001142,0.0,0.003044,0.010274,0.001142,0.002664
8,aeneid 12 mortal speech.txt,1562,91,15.054945,0.197802,5.304348,0.001280,0.0,0.000000,0.080666,...,0.048656,0.031370,0.000000,0.0,0.000000,0.0,0.001921,0.007682,0.000640,0.002561
9,aeneid 2 mortal speech.txt,1995,116,15.025862,0.267241,5.105263,0.001504,0.0,0.000000,0.097744,...,0.029073,0.034586,0.000000,0.0,0.000000,0.0,0.001504,0.012030,0.001003,0.002005
10,aeneid 3 mortal speech.txt,2105,110,16.654545,0.263636,6.545455,0.001900,0.0,0.000000,0.089311,...,0.026128,0.032779,0.000000,0.0,0.000950,0.0,0.000950,0.003800,0.000000,0.000000
12,aeneid 4 mortal speech.txt,2147,132,14.196970,0.204545,5.606061,0.001863,0.0,0.000000,0.095482,...,0.034467,0.027014,0.000000,0.0,0.000932,0.0,0.004658,0.006521,0.000932,0.001397
13,aeneid 5 mortal speech.txt,1391,82,14.756098,0.256098,6.185185,0.001438,0.0,0.000000,0.089863,...,0.030194,0.025162,0.000000,0.0,0.000000,0.0,0.003595,0.012940,0.001438,0.000000
14,aeneid 6 mortal speech.txt,3691,192,16.755208,0.276042,6.064516,0.001355,0.0,0.000542,0.089949,...,0.025738,0.034137,0.000271,0.0,0.001084,0.0,0.002980,0.005690,0.000813,0.001897
16,aeneid 7 mortal speech.txt,926,43,18.790698,0.209302,8.181818,0.000000,0.0,0.000000,0.097192,...,0.028078,0.029158,0.000000,0.0,0.000000,0.0,0.002160,0.014039,0.000000,0.002160
18,aeneid 8 mortal speech.txt,2091,93,19.548387,0.279570,6.870968,0.000000,0.0,0.000000,0.095648,...,0.025347,0.023912,0.000000,0.0,0.000956,0.0,0.002391,0.004782,0.001435,0.002869
19,aeneid 9 mortal speech.txt,1706,106,14.037736,0.320755,5.000000,0.000586,0.0,0.000000,0.082649,...,0.040445,0.031067,0.000000,0.0,0.000000,0.0,0.002931,0.007620,0.001172,0.000000
20,divine_speech_thebaid_1.txt,637,34,16.264706,0.176471,6.857143,0.000000,0.0,0.000000,0.073783,...,0.018838,0.023548,0.000000,0.0,0.003140,0.0,0.001570,0.004710,0.001570,0.001570
21,divine_speech_thebaid_11.txt,554,37,13.081081,0.162162,6.285714,0.000000,0.0,0.000000,0.102888,...,0.023466,0.018051,0.000000,0.0,0.000000,0.0,0.001805,0.001805,0.000000,0.001805
22,divine_speech_thebaid_3.txt,550,21,22.904762,0.190476,7.400000,0.000000,0.0,0.000000,0.105455,...,0.041818,0.040000,0.000000,0.0,0.000000,0.0,0.000000,0.001818,0.000000,0.000000
23,divine_speech_thebaid_7.txt,892,44,17.704545,0.250000,6.250000,0.001121,0.0,0.000000,0.112108,...,0.019058,0.022422,0.000000,0.0,0.002242,0.0,0.000000,0.006726,0.001121,0.002242
24,divine_speech_thebaid_8.txt,495,33,13.121212,0.151515,4.857143,0.000000,0.0,0.000000,0.090909,...,0.044444,0.016162,0.000000,0.0,0.002020,0.0,0.000000,0.010101,0.000000,0.000000
25,divine_speech_thebaid_9.txt,854,50,14.860000,0.180000,9.200000,0.002342,0.0,0.000000,0.087822,...,0.038642,0.026932,0.000000,0.0,0.000000,0.0,0.002342,0.002342,0.000000,0.001171
26,mortal_speech_thebaid 4.txt,1309,52,21.942308,0.250000,6.071429,0.002292,0.0,0.000000,0.108480,...,0.038961,0.025974,0.000764,0.0,0.000000,0.0,0.000000,0.007639,0.001528,0.000000
27,mortal_speech_thebaid_1.txt,1982,88,19.545455,0.250000,5.250000,0.000000,0.0,0.000000,0.085267,...,0.022704,0.024218,0.000000,0.0,0.000505,0.0,0.000505,0.010091,0.001009,0.002018
28,mortal_speech_thebaid_10.txt,1611,101,13.881188,0.108911,5.333333,0.001241,0.0,0.000000,0.080074,...,0.033520,0.027933,0.000000,0.0,0.000000,0.0,0.001241,0.008070,0.001241,0.001862
29,mortal_speech_thebaid_11.txt,2207,149,12.966443,0.093960,4.875000,0.000906,0.0,0.000000,0.099683,...,0.029452,0.028999,0.000000,0.0,0.000453,0.0,0.000453,0.002719,0.000906,0.001359
30,mortal_speech_thebaid_12.txt,1750,116,13.163793,0.172414,4.619048,0.000000,0.0,0.000000,0.097714,...,0.034857,0.021143,0.000571,0.0,0.000571,0.0,0.000000,0.009714,0.001143,0.002286
31,mortal_speech_thebaid_2.txt,1717,82,18.195122,0.231707,8.695652,0.002912,0.0,0.000000,0.087944,...,0.030285,0.030868,0.000000,0.0,0.000582,0.0,0.000582,0.011066,0.000000,0.001165
32,mortal_speech_thebaid_3.txt,2067,102,17.627451,0.186275,3.920000,0.001451,0.0,0.000000,0.096275,...,0.032414,0.024190,0.000000,0.0,0.000968,0.0,0.000484,0.007257,0.000484,0.001935
33,mortal_speech_thebaid_5.txt,1042,65,13.969231,0.184615,5.000000,0.000000,0.0,0.000000,0.100768,...,0.026871,0.019194,0.000000,0.0,0.000960,0.0,0.000000,0.005758,0.000000,0.000000
34,mortal_speech_thebaid_6.txt,644,35,16.057143,0.257143,4.727273,0.001553,0.0,0.000000,0.086957,...,0.037267,0.023292,0.000000,0.0,0.000000,0.0,0.001553,0.006211,0.000000,0.000000
35,mortal_speech_thebaid_7.txt,1699,87,16.965517,0.195402,6.400000,0.000589,0.0,0.000000,0.097116,...,0.022955,0.025309,0.000000,0.0,0.000000,0.0,0.000589,0.004120,0.001766,0.000000
36,mortal_speech_thebaid_8.txt,1312,74,15.513514,0.216216,4.619048,0.000000,0.0,0.000762,0.105945,...,0.031250,0.016768,0.000000,0.0,0.000762,0.0,0.000000,0.005335,0.001524,0.000762
37,mortal_speech_thebaid_9.txt,1300,74,15.270270,0.121622,8.444444,0.002308,0.0,0.000000,0.095385,...,0.032308,0.026923,0.000000,0.0,0.001538,0.0,0.000000,0.006154,0.000769,0.001538

In [81]:
df_mortal_divine_no_juturna = df_mortal_divine[df_mortal_divine['File Name'] != 'aeneid 12 divine speech.txt']
df_mortal_divine_no_juturna.to_csv('mortal_divine_no_juturna_speech.csv')
df_mortal_divine_no_juturna

,File Name,word_count,sentence_count,sentence_length,fraction_sentence_relative,relative_clause_length,alius,antequam,atque_consonant,conjunction,...,personal,preposition,priusquam,quidam,quin,quominus,reflexive,si,superlative,ut
0,aeneid 1 divine speech.txt,1414,64,19.234375,0.328125,5.560000,0.000707,0.0,0.000000,0.089109,...,0.027581,0.027581,0.000000,0.0,0.000707,0.0,0.002122,0.001414,0.001414,0.002829
2,aeneid 10 divine speech.txt,1142,70,14.228571,0.142857,4.538462,0.000876,0.0,0.001751,0.095447,...,0.017513,0.024518,0.000000,0.0,0.002627,0.0,0.000876,0.008757,0.000876,0.003503
4,aeneid 11 divine speech.txt,539,27,17.333333,0.074074,5.666667,0.001855,0.0,0.000000,0.068646,...,0.014842,0.044527,0.000000,0.0,0.000000,0.0,0.007421,0.000000,0.000000,0.003711
6,aeneid 12 divine speech no juturna.txt,486,29,14.655172,0.206897,4.166667,0.000000,0.0,0.000000,0.092593,...,0.026749,0.034979,0.000000,0.0,0.000000,0.0,0.000000,0.004115,0.002058,0.008230
11,aeneid 4 divine speech.txt,554,37,13.027027,0.216216,5.625000,0.000000,0.0,0.000000,0.108303,...,0.034296,0.021661,0.000000,0.0,0.001805,0.0,0.000000,0.012635,0.000000,0.000000
15,aeneid 7 divine speech.txt,626,35,15.628571,0.200000,6.300000,0.000000,0.0,0.004792,0.087859,...,0.031949,0.035144,0.000000,0.0,0.003195,0.0,0.000000,0.007987,0.000000,0.001597
17,aeneid 8 divine speech.txt,465,26,15.576923,0.307692,6.000000,0.002151,0.0,0.000000,0.073118,...,0.038710,0.025806,0.000000,0.0,0.000000,0.0,0.000000,0.004301,0.004301,0.002151
1,aeneid 1 mortal speech.txt,1178,65,15.846154,0.215385,4.562500,0.000000,0.0,0.000849,0.094228,...,0.029711,0.032258,0.000000,0.0,0.000000,0.0,0.001698,0.010187,0.000849,0.000849
3,aeneid 10 mortal speech.txt,1012,79,11.151899,0.202532,4.647059,0.000000,0.0,0.000000,0.074111,...,0.041502,0.028656,0.000000,0.0,0.000000,0.0,0.000988,0.003953,0.002964,0.000988
5,aeneid 11 mortal speech.txt,2628,145,15.827586,0.275862,5.936170,0.001903,0.0,0.000000,0.095129,...,0.028539,0.031963,0.000000,0.0,0.001142,0.0,0.003044,0.010274,0.001142,0.002664
8,aeneid 12 mortal speech.txt,1562,91,15.054945,0.197802,5.304348,0.001280,0.0,0.000000,0.080666,...,0.048656,0.031370,0.000000,0.0,0.000000,0.0,0.001921,0.007682,0.000640,0.002561
9,aeneid 2 mortal speech.txt,1995,116,15.025862,0.267241,5.105263,0.001504,0.0,0.000000,0.097744,...,0.029073,0.034586,0.000000,0.0,0.000000,0.0,0.001504,0.012030,0.001003,0.002005
10,aeneid 3 mortal speech.txt,2105,110,16.654545,0.263636,6.545455,0.001900,0.0,0.000000,0.089311,...,0.026128,0.032779,0.000000,0.0,0.000950,0.0,0.000950,0.003800,0.000000,0.000000
12,aeneid 4 mortal speech.txt,2147,132,14.196970,0.204545,5.606061,0.001863,0.0,0.000000,0.095482,...,0.034467,0.027014,0.000000,0.0,0.000932,0.0,0.004658,0.006521,0.000932,0.001397
13,aeneid 5 mortal speech.txt,1391,82,14.756098,0.256098,6.185185,0.001438,0.0,0.000000,0.089863,...,0.030194,0.025162,0.000000,0.0,0.000000,0.0,0.003595,0.012940,0.001438,0.000000
14,aeneid 6 mortal speech.txt,3691,192,16.755208,0.276042,6.064516,0.001355,0.0,0.000542,0.089949,...,0.025738,0.034137,0.000271,0.0,0.001084,0.0,0.002980,0.005690,0.000813,0.001897
16,aeneid 7 mortal speech.txt,926,43,18.790698,0.209302,8.181818,0.000000,0.0,0.000000,0.097192,...,0.028078,0.029158,0.000000,0.0,0.000000,0.0,0.002160,0.014039,0.000000,0.002160
18,aeneid 8 mortal speech.txt,2091,93,19.548387,0.279570,6.870968,0.000000,0.0,0.000000,0.095648,...,0.025347,0.023912,0.000000,0.0,0.000956,0.0,0.002391,0.004782,0.001435,0.002869
19,aeneid 9 mortal speech.txt,1706,106,14.037736,0.320755,5.000000,0.000586,0.0,0.000000,0.082649,...,0.040445,0.031067,0.000000,0.0,0.000000,0.0,0.002931,0.007620,0.001172,0.000000
20,divine_speech_thebaid_1.txt,637,34,16.264706,0.176471,6.857143,0.000000,0.0,0.000000,0.073783,...,0.018838,0.023548,0.000000,0.0,0.003140,0.0,0.001570,0.004710,0.001570,0.001570
21,divine_speech_thebaid_11.txt,554,37,13.081081,0.162162,6.285714,0.000000,0.0,0.000000,0.102888,...,0.023466,0.018051,0.000000,0.0,0.000000,0.0,0.001805,0.001805,0.000000,0.001805
22,divine_speech_thebaid_3.txt,550,21,22.904762,0.190476,7.400000,0.000000,0.0,0.000000,0.105455,...,0.041818,0.040000,0.000000,0.0,0.000000,0.0,0.000000,0.001818,0.000000,0.000000
23,divine_speech_thebaid_7.txt,892,44,17.704545,0.250000,6.250000,0.001121,0.0,0.000000,0.112108,...,0.019058,0.022422,0.000000,0.0,0.002242,0.0,0.000000,0.006726,0.001121,0.002242
24,divine_speech_thebaid_8.txt,495,33,13.121212,0.151515,4.857143,0.000000,0.0,0.000000,0.090909,...,0.044444,0.016162,0.000000,0.0,0.002020,0.0,0.000000,0.010101,0.000000,0.000000
25,divine_speech_thebaid_9.txt,854,50,14.860000,0.180000,9.200000,0.002342,0.0,0.000000,0.087822,...,0.038642,0.026932,0.000000,0.0,0.000000,0.0,0.002342,0.002342,0.000000,0.001171
26,mortal_speech_thebaid 4.txt,1309,52,21.942308,0.250000,6.071429,0.002292,0.0,0.000000,0.108480,...,0.038961,0.025974,0.000764,0.0,0.000000,0.0,0.000000,0.007639,0.001528,0.000000
27,mortal_speech_thebaid_1.txt,1982,88,19.545455,0.250000,5.250000,0.000000,0.0,0.000000,0.085267,...,0.022704,0.024218,0.000000,0.0,0.000505,0.0,0.000505,0.010091,0.001009,0.002018
28,mortal_speech_thebaid_10.txt,1611,101,13.881188,0.108911,5.333333,0.001241,0.0,0.000000,0.080074,...,0.033520,0.027933,0.000000,0.0,0.000000,0.0,0.001241,0.008070,0.001241,0.001862
29,mortal_speech_thebaid_11.txt,2207,149,12.966443,0.093960,4.875000,0.000906,0.0,0.000000,0.099683,...,0.029452,0.028999,0.000000,0.0,0.000453,0.0,0.000453,0.002719,0.000906,0.001359
30,mortal_speech_thebaid_12.txt,1750,116,13.163793,0.172414,4.619048,0.000000,0.0,0.000000,0.097714,...,0.034857,0.021143,0.000571,0.0,0.000571,0.0,0.000000,0.009714,0.001143,0.002286
31,mortal_speech_thebaid_2.txt,1717,82,18.195122,0.231707,8.695652,0.002912,0.0,0.000000,0.087944,...,0.030285,0.030868,0.000000,0.0,0.000582,0.0,0.000582,0.011066,0.000000,0.001165
32,mortal_speech_thebaid_3.txt,2067,102,17.627451,0.186275,3.920000,0.001451,0.0,0.000000,0.096275,...,0.032414,0.024190,0.000000,0.0,0.000968,0.0,0.000484,0.007257,0.000484,0.001935
33,mortal_speech_thebaid_5.txt,1042,65,13.969231,0.184615,5.000000,0.000000,0.0,0.000000,0.100768,...,0.026871,0.019194,0.000000,0.0,0.000960,0.0,0.000000,0.005758,0.000000,0.000000
34,mortal_speech_thebaid_6.txt,644,35,16.057143,0.257143,4.727273,0.001553,0.0,0.000000,0.086957,...,0.037267,0.023292,0.000000,0.0,0.000000,0.0,0.001553,0.006211,0.000000,0.000000
35,mortal_speech_thebaid_7.txt,1699,87,16.965517,0.195402,6.400000,0.000589,0.0,0.000000,0.097116,...,0.022955,0.025309,0.000000,0.0,0.000000,0.0,0.000589,0.004120,0.001766,0.000000
36,mortal_speech_thebaid_8.txt,1312,74,15.513514,0.216216,4.619048,0.000000,0.0,0.000762,0.105945,...,0.031250,0.016768,0.000000,0.0,0.000762,0.0,0.000000,0.005335,0.001524,0.000762
37,mortal_speech_thebaid_9.txt,1300,74,15.270270,0.121622,8.444444,0.002308,0.0,0.000000,0.095385,...,0.032308,0.026923,0.000000,0.0,0.001538,0.0,0.000000,0.006154,0.000769,0.001538

In [88]:
# variables to focus on
# age
# education
# chronotype
# literary experience

In [89]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os
import re
import pandas as pd
from sklearn.decomposition import PCA
#import matplotlib.pyplot as plt
import numpy as np

from datetime import datetime

In [90]:
# load text data

df_WWC = pd.read_csv('merged_dataset_v3.csv')
df_WWC.head()

/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/413186783.py:3: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df_WWC = pd.read_csv('merged_dataset_v3.csv')

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,Texto_tokenized_sa_num_syll_mediana_psyco,Texto_tokenized_sa_num_syll_curtosis_psyco,Texto_tokenized_sa_num_syll_skewness_psyco,Texto_tokenized_sa_NP_promedio_psyco,Texto_tokenized_sa_NP_minimo_psyco,Texto_tokenized_sa_NP_maximo_psyco,Texto_tokenized_sa_NP_std_psyco,Texto_tokenized_sa_NP_mediana_psyco,Texto_tokenized_sa_NP_curtosis_psyco,Texto_tokenized_sa_NP_skewness_psyco
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,3.0,-0.052469,0.489205,15.000000,0.0,96.0,18.381644,8.0,3.273263,1.925712
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,3.0,0.759256,-0.114001,8.941176,0.0,76.0,17.058621,6.0,11.062845,3.539034
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,3.0,0.243429,0.380496,12.875000,0.0,111.0,17.310927,6.0,8.443541,2.725065
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,3.0,-0.055742,0.508188,14.035088,0.0,89.0,18.048390,7.0,3.666035,2.002149
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,3.0,0.107460,0.419077,11.509477,0.0,111.0,15.372544,6.0,8.368224,2.676734

In [91]:
df_WWC

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,Texto_tokenized_sa_num_syll_mediana_psyco,Texto_tokenized_sa_num_syll_curtosis_psyco,Texto_tokenized_sa_num_syll_skewness_psyco,Texto_tokenized_sa_NP_promedio_psyco,Texto_tokenized_sa_NP_minimo_psyco,Texto_tokenized_sa_NP_maximo_psyco,Texto_tokenized_sa_NP_std_psyco,Texto_tokenized_sa_NP_mediana_psyco,Texto_tokenized_sa_NP_curtosis_psyco,Texto_tokenized_sa_NP_skewness_psyco
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,3.0,-0.052469,0.489205,15.000000,0.0,96.0,18.381644,8.0,3.273263,1.925712
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,3.0,0.759256,-0.114001,8.941176,0.0,76.0,17.058621,6.0,11.062845,3.539034
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,3.0,0.243429,0.380496,12.875000,0.0,111.0,17.310927,6.0,8.443541,2.725065
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,3.0,-0.055742,0.508188,14.035088,0.0,89.0,18.048390,7.0,3.666035,2.002149
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,3.0,0.107460,0.419077,11.509477,0.0,111.0,15.372544,6.0,8.368224,2.676734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99184,NaN,NaN,97250_255155.txt,66.0,23.0,155.0,1330.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99185,NaN,NaN,97250_255155.txt,66.0,23.0,155.0,1330.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99186,NaN,NaN,97250_255155.txt,66.0,23.0,155.0,1330.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99187,NaN,NaN,97250_255155.txt,66.0,23.0,155.0,1330.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99188,NaN,NaN,97250_255155.txt,66.0,23.0,155.0,1330.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
# load demographic data

df_demo = pd.read_csv('participant_data_formatted.csv')
df_demo.head()

,Unnamed: 0,idUsuario,Respuesta_Pregunta_1,Respuesta_Pregunta_2,Respuesta_Pregunta_3,Respuesta_Pregunta_4,Respuesta_Pregunta_5,Respuesta_Pregunta_6,FechaNacimiento,Genero,...,IdUsuarioCategoria,IdUsuarioSubCategoria,IdIdioma,FechaAlta,MiembroEquipoMundial,MiembroEquipoMundialOrden,MiembroEquipoTarea,IdPais_Nacimiento,IdIdioma_Materno,EducacionFormalYYYY
0,0,user_ID,Response_to_Question_1,Response_to_Question_2,Response_to_Question_3,Response_to_Question_4,Response_to_Question_5,Response_to_Question_6,Date_of_Birth,Gender,...,User_Category_ID,User_Subcategory_ID,Language_ID,Registration_Date,Global_Team_Member,Global_Team_Member_Order,Team_Task_Member,Country_of_Birth_ID,Native_Language_ID,Formal_Education_Year
1,1,22,30,1,4,1,2,1,25-03-1971,2,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
2,2,49504,33,4,NaN,NaN,NaN,NaN,11/9/74,1,...,3,5,1,31:08.2,TRUE,3,Producci√≥n y coordinaci√≥n general,307,1,22
3,3,49505,20,2,NaN,3,1,5,25-12-1979,1,...,3,5,1,55:32.2,TRUE,5,Equipo Todo Terreno,307,1,42
4,4,49506,24,NaN,NaN,4,NaN,4,3/6/96,1,...,3,5,1,02:24.5,TRUE,6,Comunicaci√≥n,307,1,22

In [93]:
df_demo

,Unnamed: 0,idUsuario,Respuesta_Pregunta_1,Respuesta_Pregunta_2,Respuesta_Pregunta_3,Respuesta_Pregunta_4,Respuesta_Pregunta_5,Respuesta_Pregunta_6,FechaNacimiento,Genero,...,IdUsuarioCategoria,IdUsuarioSubCategoria,IdIdioma,FechaAlta,MiembroEquipoMundial,MiembroEquipoMundialOrden,MiembroEquipoTarea,IdPais_Nacimiento,IdIdioma_Materno,EducacionFormalYYYY
0,0,user_ID,Response_to_Question_1,Response_to_Question_2,Response_to_Question_3,Response_to_Question_4,Response_to_Question_5,Response_to_Question_6,Date_of_Birth,Gender,...,User_Category_ID,User_Subcategory_ID,Language_ID,Registration_Date,Global_Team_Member,Global_Team_Member_Order,Team_Task_Member,Country_of_Birth_ID,Native_Language_ID,Formal_Education_Year
1,1,22,30,1,4,1,2,1,25-03-1971,2,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
2,2,49504,33,4,NaN,NaN,NaN,NaN,11/9/74,1,...,3,5,1,31:08.2,TRUE,3,Producci√≥n y coordinaci√≥n general,307,1,22
3,3,49505,20,2,NaN,3,1,5,25-12-1979,1,...,3,5,1,55:32.2,TRUE,5,Equipo Todo Terreno,307,1,42
4,4,49506,24,NaN,NaN,4,NaN,4,3/6/96,1,...,3,5,1,02:24.5,TRUE,6,Comunicaci√≥n,307,1,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8769,8769,81091,NaN,2,NaN,NaN,NaN,NaN,19-06-1996,1,...,3,5,1,44:53.2,FALSE,0,NaN,307,1,18
8770,8770,81092,16,NaN,NaN,NaN,NaN,NaN,1/9/92,3,...,3,5,1,46:42.6,FALSE,0,NaN,418,1,20
8771,8771,81093,22,3,8,4,7,7,30-12-1988,1,...,3,5,1,48:59.6,FALSE,0,NaN,418,1,20
8772,8772,81094,21,2,NaN,NaN,NaN,NaN,11/2/01,2,...,3,5,1,50:17.0,FALSE,0,NaN,339,1,14
8773,8773,81099,NaN,3,NaN,NaN,NaN,NaN,9/10/93,1,...,3,5,1,56:28.3,FALSE,0,NaN,418,1,20

In [94]:
# extract user IDs from filenames

df_WWC['idUsuario'] = df_WWC['filename'].str.split('_').str[0]

In [95]:
df_WWC.head()

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,Texto_tokenized_sa_num_syll_curtosis_psyco,Texto_tokenized_sa_num_syll_skewness_psyco,Texto_tokenized_sa_NP_promedio_psyco,Texto_tokenized_sa_NP_minimo_psyco,Texto_tokenized_sa_NP_maximo_psyco,Texto_tokenized_sa_NP_std_psyco,Texto_tokenized_sa_NP_mediana_psyco,Texto_tokenized_sa_NP_curtosis_psyco,Texto_tokenized_sa_NP_skewness_psyco,idUsuario
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,-0.052469,0.489205,15.000000,0.0,96.0,18.381644,8.0,3.273263,1.925712,22
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,0.759256,-0.114001,8.941176,0.0,76.0,17.058621,6.0,11.062845,3.539034,22
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,0.243429,0.380496,12.875000,0.0,111.0,17.310927,6.0,8.443541,2.725065,22
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,-0.055742,0.508188,14.035088,0.0,89.0,18.048390,7.0,3.666035,2.002149,22
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,0.107460,0.419077,11.509477,0.0,111.0,15.372544,6.0,8.368224,2.676734,22

In [96]:
# merge datasets

df = pd.merge(df_WWC, df_demo, on="idUsuario")

In [97]:
df.head()

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,IdUsuarioCategoria,IdUsuarioSubCategoria,IdIdioma,FechaAlta,MiembroEquipoMundial,MiembroEquipoMundialOrden,MiembroEquipoTarea,IdPais_Nacimiento,IdIdioma_Materno,EducacionFormalYYYY
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8

In [98]:
df

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,IdUsuarioCategoria,IdUsuarioSubCategoria,IdIdioma,FechaAlta,MiembroEquipoMundial,MiembroEquipoMundialOrden,MiembroEquipoTarea,IdPais_Nacimiento,IdIdioma_Materno,EducacionFormalYYYY
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68621,NaN,NaN,80697_191733.txt,1.0,1.0,1.0,0.0,NaN,NaN,NaN,...,3,5,1,53:31.8,FALSE,0,NaN,307,1,19
68622,NaN,NaN,80723_160203.txt,0.0,0.0,0.0,0.0,NaN,NaN,NaN,...,3,5,1,11:42.8,FALSE,0,NaN,307,1,22
68623,NaN,NaN,80815_231919.txt,88.0,108.0,166.0,216.0,NaN,NaN,NaN,...,3,5,3,07:56.1,FALSE,0,NaN,324,3,25
68624,NaN,NaN,80815_255025.txt,89.0,63.0,224.0,283.0,NaN,NaN,NaN,...,3,5,3,07:56.1,FALSE,0,NaN,324,3,25
68625,NaN,NaN,80881_168977.txt,0.0,2.0,3.0,3.0,NaN,NaN,NaN,...,3,5,1,48:50.0,FALSE,0,NaN,307,1,23

In [99]:
#delete sparse rows at end

df = df.drop(df.index[68326:68627])
df

,IdIdioma_osv,Texto_osv_osv,filename,Core_universal_dependencies,Non-core_universal_dependencies,Nominal_universal_dependencies,Non-dependency_universal_dependencies,IdMundialTexto_granularidad,IdMundial_granularidad,Texto_granularidad_promedio_granularidad,...,IdUsuarioCategoria,IdUsuarioSubCategoria,IdIdioma,FechaAlta,MiembroEquipoMundial,MiembroEquipoMundialOrden,MiembroEquipoTarea,IdPais_Nacimiento,IdIdioma_Materno,EducacionFormalYYYY
0,1,0.019777141,22_153578.txt,136.0,203.0,350.0,238.0,126366.0,12.0,6.531250,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
1,1,0.022520447,22_161477.txt,82.0,92.0,199.0,168.0,134265.0,12.0,7.236364,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
2,1,0.016744167,22_169507.txt,94.0,154.0,269.0,186.0,142295.0,12.0,6.291080,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
3,1,0.017703811,22_177311.txt,87.0,127.0,237.0,138.0,150099.0,12.0,6.318750,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
4,1,0.018634681,22_183429.txt,617.0,870.0,1854.0,1108.0,156217.0,12.0,6.384232,...,3,5,1,04:32.9,TRUE,7,Desarrollo y programaci√≥n,307,1,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68321,1,0.009633,81093_268602.txt,18.0,20.0,39.0,42.0,232390.0,13.0,7.000000,...,3,5,1,48:59.6,FALSE,0,NaN,418,1,20
68322,1,0.017454,81093_271453.txt,14.0,19.0,51.0,25.0,235241.0,13.0,7.222222,...,3,5,1,48:59.6,FALSE,0,NaN,418,1,20
68323,1,0.019284,81093_274110.txt,15.0,21.0,53.0,22.0,237898.0,13.0,6.709677,...,3,5,1,48:59.6,FALSE,0,NaN,418,1,20
68324,1,0.029317,81093_276687.txt,14.0,33.0,41.0,25.0,NaN,NaN,NaN,...,3,5,1,48:59.6,FALSE,0,NaN,418,1,20
68325,1,0.017255,81094_160157.txt,34.0,65.0,51.0,64.0,132945.0,12.0,7.000000,...,3,5,1,50:17.0,FALSE,0,NaN,339,1,14

In [100]:
# Convert the date strings to a uniform datetime format
df['FechaNacimiento'] = pd.to_datetime(df['FechaNacimiento'], format='%d-%m-%Y', errors='coerce').fillna(
    pd.to_datetime(df['FechaNacimiento'], format='%d/%m/%Y', errors='coerce'))

# Reference date (January 1, 2024)
reference_date = datetime(2024, 1, 1)

# Function to calculate age
def calculate_age(birthdate, ref_date):
    return ref_date.year - birthdate.year - ((ref_date.month, ref_date.day) < (birthdate.month, birthdate.day))

# Calculate age and add to new column
df['age_as_of_2024'] = df['FechaNacimiento'].apply(lambda x: calculate_age(x, reference_date))

# Display the result
df['age_as_of_2024']
df['FechaNacimiento']

0       1971-03-25
1       1971-03-25
2       1971-03-25
3       1971-03-25
4       1971-03-25
           ...
68321   1988-12-30
68322   1988-12-30
68323   1988-12-30
68324   1988-12-30
68325          NaT
Name: FechaNacimiento, Length: 68326, dtype: datetime64[ns]

In [101]:
# export merged file
df.to_csv('merged_truncated.csv')

In [102]:
# data imputation 

col_start = 'Core_universal_dependencies'
col_end = 'Texto_tokenized_sa_NP_skewness_psyco'

# get the list of columns between the start and end columns, inclusive
col_list = df.columns[df.columns.get_loc(col_start) : df.columns.get_loc(col_end) + 1]

# loop through each column in the list
for col in col_list:
    # convert non-numeric entries to NaN
    df[col] = pd.to_numeric(df[col], errors='coerce')
    # compute the median, skipping NaN values
    median_value = df[col].median(skipna=True)
    # replace NaN with the median value
    df[col].fillna(median_value, inplace=True)

In [103]:
# remove missing ages
df = df[df['age_as_of_2024'].notna()]
df['age_as_of_2024']

0        52.0
1        52.0
2        52.0
3        52.0
4        52.0
         ...
68320    35.0
68321    35.0
68322    35.0
68323    35.0
68324    35.0
Name: age_as_of_2024, Length: 41293, dtype: float64

In [104]:
# Define bins and labels
bins = [0, 18, 23, 30, 40, 60, 70, float('inf')]
labels = ['Under 18', '18-22', '23-29', '30-39', '40-59', '60-69', '70 or above']

# Categorize ages into bins
df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)

# Display the result
print(df['age_category'])

0        40-59
1        40-59
2        40-59
3        40-59
4        40-59
         ...
68320    30-39
68321    30-39
68322    30-39
68323    30-39
68324    30-39
Name: age_category, Length: 41293, dtype: category
Categories (7, object): ['Under 18' < '18-22' < '23-29' < '30-39' < '40-59' < '60-69' < '70 or above']

/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/991509981.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)
/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/991509981.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)

In [111]:
# remove weird outliers in the education column 

# Convert 'EducacionFormalYYYY' to numeric, converting errors to NaN
df['EducacionFormalYYYY'] = pd.to_numeric(df['EducacionFormalYYYY'], errors='coerce')

# Drop rows with NaN in 'EducacionFormalYYYY'
df = df.dropna(subset=['EducacionFormalYYYY'])

# Convert 'EducacionFormalYYYY' to integer
df['EducacionFormalYYYY'] = df['EducacionFormalYYYY'].astype(int)

# Filter rows where 'EducacionFormalYYYY' <= 50 or are negative
df = df[(df['EducacionFormalYYYY'] >= 0) & (df['EducacionFormalYYYY'] <= 50)]

In [112]:
# CORRELATION BETWEEN AGE AND EDUCATION
corr_s = df['age_as_of_2024'].corr(df['EducacionFormalYYYY'],method='spearman')
print(corr_s)

0.28110339321591493

In [114]:
# FEATURE CORRELATIONS WITH EDUCATION 
# ONLY USING SPEARMAN

# Initialize an empty dictionary to store correlations
correlations = {}

for col in col_list:
    # Ensure both columns are numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df['EducacionFormalYYYY'] = pd.to_numeric(df['EducacionFormalYYYY'], errors='coerce')
    
    # Compute the correlation coefficient, skipping NaN values
    corr = df[col].corr(df['EducacionFormalYYYY'],method='spearman')
    correlations[col] = corr

# Convert the dictionary to a DataFrame for better visualization
correlation_df = pd.DataFrame.from_dict(correlations, orient='index', columns=['Correlation_with_Education'])

# Reset index to turn the index into a column
correlation_df.reset_index(inplace=True)
correlation_df.rename(columns={'index': 'Feature'}, inplace=True)

# Display the correlation DataFrame
print(correlation_df)

correlation_df.to_csv('education_correlations.csv')

                                   Feature  Correlation_with_Education
0              Core_universal_dependencies                    0.010108
1          Non-core_universal_dependencies                   -0.010464
2           Nominal_universal_dependencies                    0.056737
3    Non-dependency_universal_dependencies                    0.032944
4              IdMundialTexto_granularidad                    0.055557
..                                     ...                         ...
106     Texto_tokenized_sa_NP_maximo_psyco                   -0.003973
107        Texto_tokenized_sa_NP_std_psyco                   -0.026883
108    Texto_tokenized_sa_NP_mediana_psyco                   -0.049847
109   Texto_tokenized_sa_NP_curtosis_psyco                    0.025691
110   Texto_tokenized_sa_NP_skewness_psyco                    0.030626

[111 rows x 2 columns]

In [115]:
# EDUCATION

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

# Assuming 'df' is your DataFrame and 'col_list' is already defined

# Ensure that 'EducacionFormalYYYY' is numeric
df['EducacionFormalYYYY'] = pd.to_numeric(df['EducacionFormalYYYY'], errors='coerce')

# Set the style of the plots
sns.set_style('whitegrid')

# Specify the directory where plots will be saved
output_dir = 'scatterplots/'
os.makedirs(output_dir, exist_ok=True)

# Loop through each feature and create a scatterplot
for col in col_list:
    # Ensure the feature column is numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # Create a new figure
    plt.figure(figsize=(8, 6))
    
    # Create scatterplot
    sns.scatterplot(
        x='EducacionFormalYYYY',
        y=col,
        data=df,
        alpha=0.7,
        edgecolor=None
    )
    
    # Set title and labels
    plt.title(f'{col} vs Education')
    plt.xlabel('EducacionFormalYYYY')
    plt.ylabel(col)
    
    # Adjust layout
    plt.tight_layout()
    
    # Sanitize the feature name for filename
    safe_col = re.sub(r'[\\/*?:"<>|]', "_", col)
    
    # Define the filename
    filename = os.path.join(output_dir, f'scatterplot_{safe_col}_vs_education.png')
    
    # Save the figure as a PNG file
    plt.savefig(filename, dpi=300)
    print(f'Saved plot to {filename}')
    
    # Close the figure to free up memory
    plt.close()

Saved plot to scatterplots/scatterplot_Core_universal_dependencies_vs_education.png
Saved plot to scatterplots/scatterplot_Non-core_universal_dependencies_vs_education.png
Saved plot to scatterplots/scatterplot_Nominal_universal_dependencies_vs_education.png
Saved plot to scatterplots/scatterplot_Non-dependency_universal_dependencies_vs_education.png
Saved plot to scatterplots/scatterplot_IdMundialTexto_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_IdMundial_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_promedio_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_minimo_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_maximo_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_std_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_skewness_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_curtosis_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_mediana_granularidad_vs_education.png
Saved plot to scatterplots/scatterplot_number_of_nodes_graph_vs_education.png
Saved plot to scatterplots/scatterplot_number_of_edges_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Density_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Diameter_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Shortest Path_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Clustering Coefficient_graph_vs_education.png
Saved plot to scatterplots/scatterplot_RE_graph_vs_education.png
Saved plot to scatterplots/scatterplot_PE_graph_vs_education.png
Saved plot to scatterplots/scatterplot_LSC_graph_vs_education.png
Saved plot to scatterplots/scatterplot_LCC_graph_vs_education.png
Saved plot to scatterplots/scatterplot_nodes_per_communities_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Verb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Noun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Adverb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Adjective_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1_Pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L1__graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Verb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Noun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Adverb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Adjective_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2_Pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L2__graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Verb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Noun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Adverb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Adjective_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3_Pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_L3__graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Calc_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Verb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Noun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Adverb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Adjective_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Average Total Degree Pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Calc_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Verb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Noun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Adverb_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Adjective_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_Total Degree Pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_words_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_verbs_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_nouns_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_adverbs_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_adjectives_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_pronoun_graph_vs_education.png
Saved plot to scatterplots/scatterplot_quantity_of_conjunction_graph_vs_education.png
Saved plot to scatterplots/scatterplot_total_content_words_graph_vs_education.png
Saved plot to scatterplots/scatterplot_FRASE_readability_vs_education.png
Saved plot to scatterplots/scatterplot_Gilliam-Pe√±a-Mountain_readability_vs_education.png
Saved plot to scatterplots/scatterplot_Lix (index values)_readability_vs_education.png
Saved plot to scatterplots/scatterplot_Lix (grade levels)_readability_vs_education.png
Saved plot to scatterplots/scatterplot_Rix (index values)_readability_vs_education.png
Saved plot to scatterplots/scatterplot_Rix (grade levels)_readability_vs_education.png
Saved plot to scatterplots/scatterplot_SOL_readability_vs_education.png
Saved plot to scatterplots/scatterplot_proba_POS_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_NEG_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_NEU_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_joy_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_sadness_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_surprise_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_fear_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_disgust_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_proba_anger_pysentimiento_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_promedio_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_minimo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_maximo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_std_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_mediana_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_curtosis_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_skewness_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_promedio_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_minimo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_maximo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_std_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_mediana_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_curtosis_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_skewness_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_promedio_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_minimo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_maximo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_std_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_mediana_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_curtosis_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_skewness_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_promedio_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_minimo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_maximo_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_std_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_mediana_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_curtosis_psyco_vs_education.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_skewness_psyco_vs_education.png

In [116]:
# FEATURE CORRELATIONS WITH AGE
# ONLY USING SPEARMAN
# Initialize an empty dictionary to store correlations
correlations = {}

for col in col_list:
    # Ensure both columns are numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df['age_as_of_2024'] = pd.to_numeric(df['age_as_of_2024'], errors='coerce')
    
    # Compute the correlation coefficient, skipping NaN values
    corr = df[col].corr(df['age_as_of_2024'],method='spearman')
    correlations[col] = corr

# Convert the dictionary to a DataFrame for better visualization
correlation_df = pd.DataFrame.from_dict(correlations, orient='index', columns=['age_as_of_2024'])

# Reset index to turn the index into a column
correlation_df.reset_index(inplace=True)
correlation_df.rename(columns={'index': 'Feature'}, inplace=True)

# Display the correlation DataFrame
print(correlation_df)

correlation_df.to_csv('age_correlations.csv')

                                   Feature  age_as_of_2024
0              Core_universal_dependencies       -0.059274
1          Non-core_universal_dependencies       -0.111641
2           Nominal_universal_dependencies        0.053152
3    Non-dependency_universal_dependencies        0.013032
4              IdMundialTexto_granularidad        0.149802
..                                     ...             ...
106     Texto_tokenized_sa_NP_maximo_psyco       -0.064774
107        Texto_tokenized_sa_NP_std_psyco       -0.086132
108    Texto_tokenized_sa_NP_mediana_psyco       -0.102259
109   Texto_tokenized_sa_NP_curtosis_psyco        0.050507
110   Texto_tokenized_sa_NP_skewness_psyco        0.059310

[111 rows x 2 columns]

In [117]:
# SCATTERPLOTS

In [118]:
# AGE

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

# Assuming 'df' is your DataFrame and 'col_list' is already defined

# Ensure that 'age_as_of_2024' is numeric
df['age_as_of_2024'] = pd.to_numeric(df['age_as_of_2024'], errors='coerce')

# Set the style of the plots
sns.set_style('whitegrid')

# Specify the directory where plots will be saved
output_dir = 'scatterplots/'
os.makedirs(output_dir, exist_ok=True)

# Loop through each feature and create a scatterplot
for col in col_list:
    # Ensure the feature column is numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    
    # Create a new figure
    plt.figure(figsize=(8, 6))
    
    # Create scatterplot
    sns.scatterplot(
        x='age_as_of_2024',
        y=col,
        data=df,
        alpha=0.7,
        edgecolor=None
    )
    
    # Set title and labels
    plt.title(f'{col} vs Age')
    plt.xlabel('Age as of 2024')
    plt.ylabel(col)
    
    # Adjust layout
    plt.tight_layout()
    
    # Sanitize the feature name for filename
    safe_col = re.sub(r'[\\/*?:"<>|]', "_", col)
    
    # Define the filename
    filename = os.path.join(output_dir, f'scatterplot_{safe_col}_vs_age.png')
    
    # Save the figure as a PNG file
    plt.savefig(filename, dpi=300)
    print(f'Saved plot to {filename}')
    
    # Close the figure to free up memory
    plt.close()

Saved plot to scatterplots/scatterplot_Core_universal_dependencies_vs_age.png
Saved plot to scatterplots/scatterplot_Non-core_universal_dependencies_vs_age.png
Saved plot to scatterplots/scatterplot_Nominal_universal_dependencies_vs_age.png
Saved plot to scatterplots/scatterplot_Non-dependency_universal_dependencies_vs_age.png
Saved plot to scatterplots/scatterplot_IdMundialTexto_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_IdMundial_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_promedio_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_minimo_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_maximo_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_std_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_skewness_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_curtosis_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_granularidad_mediana_granularidad_vs_age.png
Saved plot to scatterplots/scatterplot_number_of_nodes_graph_vs_age.png
Saved plot to scatterplots/scatterplot_number_of_edges_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Density_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Diameter_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Shortest Path_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Clustering Coefficient_graph_vs_age.png
Saved plot to scatterplots/scatterplot_RE_graph_vs_age.png
Saved plot to scatterplots/scatterplot_PE_graph_vs_age.png
Saved plot to scatterplots/scatterplot_LSC_graph_vs_age.png
Saved plot to scatterplots/scatterplot_LCC_graph_vs_age.png
Saved plot to scatterplots/scatterplot_nodes_per_communities_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Verb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Noun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Adverb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Adjective_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1_Pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L1__graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Verb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Noun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Adverb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Adjective_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2_Pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L2__graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Verb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Noun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Adverb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Adjective_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3_Pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_L3__graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Calc_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Verb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Noun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Adverb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Adjective_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Average Total Degree Pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Calc_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Verb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Noun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Adverb_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Adjective_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_Total Degree Pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_words_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_verbs_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_nouns_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_adverbs_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_adjectives_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_pronoun_graph_vs_age.png
Saved plot to scatterplots/scatterplot_quantity_of_conjunction_graph_vs_age.png
Saved plot to scatterplots/scatterplot_total_content_words_graph_vs_age.png
Saved plot to scatterplots/scatterplot_FRASE_readability_vs_age.png
Saved plot to scatterplots/scatterplot_Gilliam-Pe√±a-Mountain_readability_vs_age.png
Saved plot to scatterplots/scatterplot_Lix (index values)_readability_vs_age.png
Saved plot to scatterplots/scatterplot_Lix (grade levels)_readability_vs_age.png
Saved plot to scatterplots/scatterplot_Rix (index values)_readability_vs_age.png
Saved plot to scatterplots/scatterplot_Rix (grade levels)_readability_vs_age.png
Saved plot to scatterplots/scatterplot_SOL_readability_vs_age.png
Saved plot to scatterplots/scatterplot_proba_POS_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_NEG_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_NEU_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_joy_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_sadness_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_surprise_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_fear_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_disgust_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_proba_anger_pysentimiento_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_promedio_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_minimo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_maximo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_std_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_mediana_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_curtosis_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_log_frq_skewness_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_promedio_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_minimo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_maximo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_std_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_mediana_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_curtosis_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_phon_skewness_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_promedio_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_minimo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_maximo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_std_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_mediana_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_curtosis_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_num_syll_skewness_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_promedio_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_minimo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_maximo_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_std_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_mediana_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_curtosis_psyco_vs_age.png
Saved plot to scatterplots/scatterplot_Texto_tokenized_sa_NP_skewness_psyco_vs_age.png

In [119]:
df['EducacionFormalYYYY']

0         8
1         8
2         8
3         8
4         8
         ..
68320    20
68321    20
68322    20
68323    20
68324    20
Name: EducacionFormalYYYY, Length: 41105, dtype: int64

In [18]:
# remove missing ages
df = df[df['age_as_of_2024'].notna()]
df['age_as_of_2024']

0        52.0
1        52.0
2        52.0
3        52.0
4        52.0
         ...
68320    35.0
68321    35.0
68322    35.0
68323    35.0
68324    35.0
Name: age_as_of_2024, Length: 41293, dtype: float64

In [19]:
# Define bins and labels
bins = [0, 18, 23, 30, 40, 60, 70, float('inf')]
labels = ['Under 18', '18-22', '23-29', '30-39', '40-59', '60-69', '70 or above']

# Categorize ages into bins
df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)

# Display the result
print(df['age_category'])

0        40-59
1        40-59
2        40-59
3        40-59
4        40-59
         ...
68320    30-39
68321    30-39
68322    30-39
68323    30-39
68324    30-39
Name: age_category, Length: 41293, dtype: category
Categories (7, object): ['Under 18' < '18-22' < '23-29' < '30-39' < '40-59' < '60-69' < '70 or above']

/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/991509981.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)
/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/991509981.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_category'] = pd.cut(df['age_as_of_2024'], bins=bins, labels=labels, right=False)

In [20]:
corr = df['age_as_of_2024'].corr(df['EducacionFormalYYYY'],method='spearman')
corr

np.float64(0.27906108788167483)

In [22]:
# Initialize an empty dictionary to store correlations
correlations = {}

for col in col_list:
    # Ensure both columns are numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df['age_as_of_2024'] = pd.to_numeric(df['age_as_of_2024'], errors='coerce')
    
    # Compute the correlation coefficient, skipping NaN values
    corr = df[col].corr(df['age_as_of_2024'])
    correlations[col] = corr

# Convert the dictionary to a DataFrame for better visualization
correlation_df = pd.DataFrame.from_dict(correlations, orient='index', columns=['Correlation_with_Age'])

# Reset index to turn the index into a column
correlation_df.reset_index(inplace=True)
correlation_df.rename(columns={'index': 'Feature'}, inplace=True)

# Display the correlation DataFrame
print(correlation_df)

correlation_df.to_csv('age_correlations.csv')

                                   Feature  Correlation_with_Age
0              Core_universal_dependencies             -0.053442
1          Non-core_universal_dependencies             -0.071983
2           Nominal_universal_dependencies             -0.006325
3    Non-dependency_universal_dependencies             -0.027945
4              IdMundialTexto_granularidad              0.154372
..                                     ...                   ...
106     Texto_tokenized_sa_NP_maximo_psyco             -0.068891
107        Texto_tokenized_sa_NP_std_psyco             -0.082955
108    Texto_tokenized_sa_NP_mediana_psyco             -0.092207
109   Texto_tokenized_sa_NP_curtosis_psyco              0.064585
110   Texto_tokenized_sa_NP_skewness_psyco              0.069965

[111 rows x 2 columns]

/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/300615567.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/300615567.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['age_as_of_2024'] = pd.to_numeric(df['age_as_of_2024'], errors='coerce')

In [23]:
# Initialize an empty dictionary to store correlations
correlations = {}

for col in col_list:
    # Ensure both columns are numeric
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df['EducacionFormalYYYY'] = pd.to_numeric(df['EducacionFormalYYYY'], errors='coerce')
    
    # Compute the correlation coefficient, skipping NaN values
    corr = df[col].corr(df['EducacionFormalYYYY'])
    correlations[col] = corr

# Convert the dictionary to a DataFrame for better visualization
correlation_df = pd.DataFrame.from_dict(correlations, orient='index', columns=['Correlation_with_Education'])

# Reset index to turn the index into a column
correlation_df.reset_index(inplace=True)
correlation_df.rename(columns={'index': 'Feature'}, inplace=True)

# Display the correlation DataFrame
print(correlation_df)

correlation_df.to_csv('education_correlations.csv')

                                   Feature  Correlation_with_Education
0              Core_universal_dependencies                    0.001910
1          Non-core_universal_dependencies                   -0.000221
2           Nominal_universal_dependencies                    0.002839
3    Non-dependency_universal_dependencies                    0.001106
4              IdMundialTexto_granularidad                    0.003719
..                                     ...                         ...
106     Texto_tokenized_sa_NP_maximo_psyco                    0.004655
107        Texto_tokenized_sa_NP_std_psyco                   -0.005239
108    Texto_tokenized_sa_NP_mediana_psyco                   -0.000787
109   Texto_tokenized_sa_NP_curtosis_psyco                    0.009380
110   Texto_tokenized_sa_NP_skewness_psyco                    0.008162

[111 rows x 2 columns]

/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/1663982872.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_numeric(df[col], errors='coerce')
/var/folders/qt/wx4bttqn4h13mk9smx_yjchc0000gn/T/ipykernel_81094/1663982872.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EducacionFormalYYYY'] = pd.to_numeric(df['EducacionFormalYYYY'], errors='coerce')

In [9]:
# Function to replace non-numeric values with NaN and then fill NaNs with column mean
def clean_column(col):
    col = pd.to_numeric(col, errors='coerce')
    return col.fillna(col.mean())

In [ ]:
# Optional: If your dataset has a target column, separate it
target = df_WWC['filename']
data = data.drop('target_column_name', axis=1)

In [11]:
# Apply the function to each column in the dataframe
df_WWC = df_WWC.apply(clean_column)

In [14]:
# Standardizing the Data (important for PCA)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df_WWC)

/Users/jpd/Documents/env/lib/python3.9/site-packages/sklearn/utils/extmath.py:1140: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/Users/jpd/Documents/env/lib/python3.9/site-packages/sklearn/utils/extmath.py:1145: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/Users/jpd/Documents/env/lib/python3.9/site-packages/sklearn/utils/extmath.py:1165: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

In [15]:
# Performing PCA
pca = PCA(n_components=2)  # Change n_components to the number of principal components you want
principal_components = pca.fit_transform(scaled_data)

ValueError: Input X contains NaN.
PCA does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
import pandas as pd
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

# Load the dataset
# Replace 'your_dataset.csv' with your actual file path
data = pd.read_csv('your_dataset.csv')

# Function to replace non-numeric values with NaN and then fill NaNs with column mean
def clean_column(col):
    col = pd.to_numeric(col, errors='coerce')
    return col.fillna(col.mean())

# Apply the function to each column in the dataframe
data = data.apply(clean_column)

# Optional: If your dataset has a target column, separate it
# target = data['target_column_name']
# data = data.drop('target_column_name', axis=1)

# Standardizing the Data (important for PCA)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

# Performing PCA
pca = PCA(n_components=2)  # Change n_components to the number of principal components you want
principal_components = pca.fit_transform(scaled_data)

# Creating a DataFrame with the principal components
pc_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])

# Optional: Adding the target column back if it was separated earlier
# pc_df = pd.concat([pc_df, target], axis=1)

# Plotting the principal components
plt.figure(figsize=(8, 6))
plt.scatter(pc_df['PC1'], pc_df['PC2'])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('2D PCA')
plt.grid()
plt.show()

# Explained variance
print('Explained variance ratio:', pca.explained_variance_ratio_)
print('Singular values:', pca.singular_values_)

# Save the principal components to a CSV file
pc_df.to_csv('principal_components.csv', index=False)

In [9]:
df_WWC.FRASE_readability.dropna()

0        2.0
1        4.0
2        2.0
3        3.0
4        3.0
        ...
98158    2.0
98159    2.0
98160    2.0
98161    2.0
98162    2.0
Name: FRASE_readability, Length: 98163, dtype: float64

In [10]:
df_WWC.FRASE_readability

0        2.0
1        4.0
2        2.0
3        3.0
4        3.0
        ...
99233    NaN
99234    NaN
99235    NaN
99236    NaN
99237    NaN
Name: FRASE_readability, Length: 99238, dtype: float64

In [26]:
## Constants

CORPUS_PATH = 'dataset_as_files'
STOPWORDS = stopwords.words('spanish')

In [27]:
# Change to glob

files = [file for file in os.listdir(CORPUS_PATH) if file.endswith('.txt')]

In [28]:
def preprocess_text(text):
    # Helper function for preprocessing text
    text = text.lower()
    text = re.sub('[^a-zA-Z]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

In [29]:
def stream_texts(files, preprocess=True):
    # Helper function to stream and preprocessed corpus
    for file in files:
        with open(f'{CORPUS_PATH}/{file}', 'r') as f:
            contents = f.read()
            sents = nltk.sent_tokenize(contents)
            if preprocess:
                sents = [preprocess_text(sent) for sent in sents]
            token_sents = [nltk.word_tokenize(sent) for sent in sents]
            token_sents = [[token for token in token_sent if token not in STOPWORDS] for token_sent in token_sents]
            yield token_sents

In [30]:
class SentenceIterator:
    # Cf. https://stackoverflow.com/a/55091252
    def __init__(self, path, preprocess=True):
        self.path = path
        self.preprocess = preprocess

    def __iter__(self):
        files = [file for file in os.listdir(self.path) if file.endswith('.txt')]
        for file in files:
            with open(f'{self.path}/{file}', 'r') as f:
                contents = f.read()
                sents = nltk.sent_tokenize(contents)
                if self.preprocess:
                    sents = [preprocess_text(sent) for sent in sents]
                token_sents = [nltk.word_tokenize(sent) for sent in sents]
                token_sents = [[token for token in token_sent if token not in STOPWORDS] for token_sent in token_sents]
                for token_sent in token_sents:
                    yield token_sent

In [31]:
sentences = SentenceIterator(CORPUS_PATH)
w2v_model = Word2Vec(sentences, vector_size=100, window=5, min_count=5)
w2v_model.save('wwc_w2v_size100_window5_min5.model')